"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminButton, AdminEmptyState, AdminField, AdminHeader, AdminPage, AdminSection, AdminSectionHeader } from "@/components/admin/AdminUI";

type Stage={title:string;description:string;durationDays?:number;clientVisible?:boolean};
type Template={id:number;slug:string;name:string;description:string;customized:boolean;stages:Stage[]};

export default function TemplateLibraryPage(){
 const[templates,setTemplates]=useState<Template[]>([]);const[selectedId,setSelectedId]=useState<number|null>(null);const[draft,setDraft]=useState<Stage[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 const selected=useMemo(()=>templates.find(item=>item.id===selectedId)||templates[0]||null,[templates,selectedId]);
 async function load(){setLoading(true);const response=await fetch("/api/admin/workflow-templates",{cache:"no-store"});const data=await response.json();setTemplates(Array.isArray(data)?data:[]);if(Array.isArray(data)&&data.length&&!selectedId)setSelectedId(data[0].id);setLoading(false)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(selected)setDraft(selected.stages.map(stage=>({...stage})))},[selected?.id,selected?.customized]);
 function patch(index:number,update:Partial<Stage>){setDraft(current=>current.map((stage,i)=>i===index?{...stage,...update}:stage))}
 function move(index:number,direction:-1|1){setDraft(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next})}
 function add(){setDraft(current=>[...current,{title:"New stage",description:"",durationDays:current.length?Number(current[current.length-1].durationDays||0)+1:0,clientVisible:true}])}
 async function save(){if(!selected||saving)return;setSaving(true);setMessage("");const response=await fetch("/api/admin/workflow-templates",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceId:selected.id,stages:draft})});const data=await response.json();if(response.ok){setTemplates(current=>current.map(item=>item.id===selected.id?data:item));setMessage("Template saved. New approvals will use these stages.")}else setMessage(data?.error||"Unable to save template");setSaving(false)}
 async function reset(){if(!selected||saving||!window.confirm(`Reset ${selected.name} to the UPZ default workflow?`))return;setSaving(true);const response=await fetch(`/api/admin/workflow-templates?serviceId=${selected.id}`,{method:"DELETE"});const data=await response.json();if(response.ok){setTemplates(current=>current.map(item=>item.id===selected.id?data:item));setDraft(data.stages);setMessage("Template reset to the UPZ default.")}setSaving(false)}
 if(loading)return <AdminPage><AdminEmptyState>Loading template library...</AdminEmptyState></AdminPage>;
 return <AdminPage className="template-library-page"><AdminHeader eyebrow="UPZ Workspace" title="Template Library" description="Edit the default work stages used when approving new service requests. Every approval can still be adjusted before launch, and live work orders can still add exception stages." actions={<AdminButton href="/admin/services">Manage Services</AdminButton>}/>
 <section className="template-library-layout"><AdminSection className="template-service-list"><AdminSectionHeader eyebrow="Services" title="Workflow templates"/><div>{templates.map(template=><button type="button" className={selected?.id===template.id?"active":""} key={template.id} onClick={()=>{setSelectedId(template.id);setMessage("")}}><span><strong>{template.name}</strong><small>{template.stages.length} stages</small></span><em>{template.customized?"Custom":"Default"}</em></button>)}</div></AdminSection>
 {selected&&<AdminSection className="template-editor"><AdminSectionHeader eyebrow="Workflow Template" title={selected.name} actions={<div className="template-header-actions"><AdminButton variant="outline" type="button" onClick={add}>Add Stage</AdminButton>{selected.customized&&<AdminButton variant="ghost" type="button" onClick={reset}>Reset Default</AdminButton>}</div>}/><p>{selected.description}</p><div className="template-stage-list">{draft.map((stage,index)=><article key={`${selected.id}-${index}`}><div className="template-stage-number"><span>Stage</span><strong>{index+1}</strong></div><div className="template-stage-fields"><AdminField label="Stage name"><input value={stage.title} onChange={event=>patch(index,{title:event.target.value})}/></AdminField><AdminField label="Days from start"><input type="number" min="0" value={stage.durationDays??index} onChange={event=>patch(index,{durationDays:Number(event.target.value)})}/></AdminField><AdminField label="Description" className="wide"><textarea value={stage.description||""} onChange={event=>patch(index,{description:event.target.value})}/></AdminField><label className="template-client-visible"><input type="checkbox" checked={stage.clientVisible!==false} onChange={event=>patch(index,{clientVisible:event.target.checked})}/> Show this stage to clients</label></div><div className="template-stage-actions"><AdminButton variant="ghost" type="button" disabled={index===0} onClick={()=>move(index,-1)}>Move Up</AdminButton><AdminButton variant="ghost" type="button" disabled={index===draft.length-1} onClick={()=>move(index,1)}>Move Down</AdminButton><AdminButton variant="danger" type="button" onClick={()=>setDraft(current=>current.filter((_,i)=>i!==index))}>Remove</AdminButton></div></article>)}</div><div className="template-save-bar"><div><strong>{draft.length} stages</strong><span>{selected.customized?"Custom template":"UPZ default template"}</span></div><AdminButton type="button" onClick={save} disabled={saving||!draft.some(stage=>stage.title.trim())}>{saving?"Saving...":"Save Template"}</AdminButton></div>{message&&<p className="admin-inline-success">{message}</p>}</AdminSection>}</section></AdminPage>
}
