"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminButton, AdminCard, AdminEmptyState, AdminField, AdminFormGrid, AdminHeader, AdminPage, AdminSection, AdminSectionHeader, AdminTabs, AdminToolbar } from "@/components/admin/AdminUI";

type Stage={title:string;description:string;durationDays?:number;clientVisible?:boolean};
type Template={id:number;slug:string;name:string;description:string;customized:boolean;stages:Stage[]};

export default function WorkflowTemplatesPage(){
 const[templates,setTemplates]=useState<Template[]>([]);const[selectedId,setSelectedId]=useState<number|null>(null);const[draft,setDraft]=useState<Stage[]>([]);const[query,setQuery]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 const selected=useMemo(()=>templates.find(item=>item.id===selectedId)||templates[0]||null,[templates,selectedId]);
 const filtered=useMemo(()=>templates.filter(template=>`${template.name} ${template.description}`.toLowerCase().includes(query.toLowerCase())),[templates,query]);
 async function load(){setLoading(true);const response=await fetch("/api/admin/workflow-templates",{cache:"no-store"});const data=await response.json();const next=Array.isArray(data)?data:[];setTemplates(next);if(next.length&&!selectedId)setSelectedId(next[0].id);setLoading(false)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(selected)setDraft(selected.stages.map(stage=>({...stage})))},[selected?.id,selected?.customized]);
 function patch(index:number,update:Partial<Stage>){setDraft(current=>current.map((stage,i)=>i===index?{...stage,...update}:stage))}
 function move(index:number,direction:-1|1){setDraft(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next})}
 function add(){setDraft(current=>[...current,{title:"New stage",description:"",durationDays:current.length?Number(current[current.length-1].durationDays||0)+1:0,clientVisible:true}])}
 async function save(){if(!selected||saving)return;setSaving(true);setMessage("");const response=await fetch("/api/admin/workflow-templates",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceId:selected.id,stages:draft})});const data=await response.json();if(response.ok){setTemplates(current=>current.map(item=>item.id===selected.id?data:item));setMessage("Workflow template saved. New approvals will use these work stages.")}else setMessage(data?.error||"Unable to save workflow template");setSaving(false)}
 async function reset(){if(!selected||saving||!window.confirm(`Reset ${selected.name} to the UPZ default workflow?`))return;setSaving(true);const response=await fetch(`/api/admin/workflow-templates?serviceId=${selected.id}`,{method:"DELETE"});const data=await response.json();if(response.ok){setTemplates(current=>current.map(item=>item.id===selected.id?data:item));setDraft(data.stages);setMessage("Workflow reset to the UPZ default.")}setSaving(false)}
 if(loading)return <AdminPage><AdminEmptyState>Loading workflow templates...</AdminEmptyState></AdminPage>;
 return <AdminPage className="admin-service-editor-page"><AdminHeader eyebrow="Operations Setup" title="Workflow Templates" description="Manage the reusable work stages applied during request approval. Each work order can still be adjusted before launch and during production." actions={<AdminButton href="/admin/services">Manage Services</AdminButton>}/>
 <AdminSection className="service-editor-shell"><aside className="service-editor-list"><AdminSectionHeader eyebrow="Workflow Setup" title="Work Stage Templates"/><input className="service-library-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search workflows..."/><AdminTabs className="service-editor-nav">{filtered.map(template=><button type="button" key={template.id} className={selected?.id===template.id?"active":""} onClick={()=>{setSelectedId(template.id);setMessage("")}}><strong>{template.name}</strong><span>{template.stages.length} stages · {template.customized?"Custom":"Default"}</span></button>)}</AdminTabs></aside>
 {selected&&<div className="service-editor-workspace"><AdminToolbar className="service-editor-toolbar"><div><span className="admin-ui-eyebrow">Editing Workflow</span><h2>{selected.name}</h2></div><div className="service-editor-actions">{selected.customized&&<AdminButton variant="outline" type="button" onClick={reset} disabled={saving}>Reset Default</AdminButton>}<AdminButton type="button" onClick={save} disabled={saving||!draft.some(stage=>stage.title.trim())}>{saving?"Saving...":"Save Workflow"}</AdminButton></div></AdminToolbar>{message&&<div className="service-editor-message">{message}</div>}<AdminCard variant="compact"><span className="admin-ui-eyebrow">Workflow Summary</span><h3>{draft.length} work stages</h3><p>{selected.description}</p></AdminCard><AdminSectionHeader eyebrow="Stage Builder" title="Default work stages" actions={<AdminButton type="button" onClick={add}>+ Add Stage</AdminButton>}/><div className="form-builder-list">{draft.map((stage,index)=><AdminCard className="form-builder-card" key={`${selected.id}-${index}`}><AdminFormGrid className="form-builder-grid"><AdminField label={`Stage ${index+1} Name`}><input value={stage.title} onChange={event=>patch(index,{title:event.target.value})}/></AdminField><AdminField label="Days From Start"><input type="number" min="0" value={stage.durationDays??index} onChange={event=>patch(index,{durationDays:Number(event.target.value)})}/></AdminField><AdminField label="Description" className="wide"><textarea value={stage.description||""} onChange={event=>patch(index,{description:event.target.value})}/></AdminField><div className="form-builder-toggles"><label><input type="checkbox" checked={stage.clientVisible!==false} onChange={event=>patch(index,{clientVisible:event.target.checked})}/>Client visible</label></div></AdminFormGrid><div className="service-editor-actions"><AdminButton variant="outline" type="button" disabled={index===0} onClick={()=>move(index,-1)}>Move Up</AdminButton><AdminButton variant="outline" type="button" disabled={index===draft.length-1} onClick={()=>move(index,1)}>Move Down</AdminButton><AdminButton variant="danger" type="button" onClick={()=>setDraft(current=>current.filter((_,i)=>i!==index))}>Remove</AdminButton></div></AdminCard>)}</div></div>}
 </AdminSection></AdminPage>;
}
