"use client";

import Link from "next/link";
import { useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";

const STATUSES=["new","quoted","approved","design","production","printing","installation","photography","review","completed"];
export default function ProjectPage(){
 const p=useParams();const router=useRouter();const slug=Array.isArray(p.slug)?p.slug[0]:String(p.slug||"");const id=Number(Array.isArray(p.id)?p.id[0]:p.id);
 const [project,setProject]=useState<any>(null);const [task,setTask]=useState("");const [note,setNote]=useState("");const [visibility,setVisibility]=useState("internal");const [message,setMessage]=useState("");
 const load=()=>fetch(`/api/admin/projects/${id}`).then(r=>r.json()).then(setProject);
 useEffect(load,[id]);
 async function save(fields:any){const r=await fetch(`/api/admin/projects/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(fields)});const d=await r.json();setProject(d);setMessage(r.ok?"Project saved.":d.error||"Unable to save");}
 async function addTask(e:React.FormEvent){e.preventDefault();if(!task.trim())return;await fetch(`/api/admin/projects/${id}/tasks`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:task})});setTask("");load();}
 async function updateTask(taskId:number,status:string){await fetch(`/api/admin/projects/${id}/tasks/${taskId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});load();}
 async function addNote(e:React.FormEvent){e.preventDefault();if(!note.trim())return;await fetch(`/api/admin/projects/${id}/notes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:note,visibility})});setNote("");load();}
 async function remove(){if(!confirm("Delete this project?"))return;await fetch(`/api/admin/projects/${id}`,{method:"DELETE"});router.push(`/admin/company/${slug}/projects`);}
 if(!project)return <main className="admin-page"><section className="admin-simple-state"><h1>Loading project...</h1></section></main>;
 return <main className="admin-page"><section className="project-shell"><div className="admin-detail-topbar"><Link href={`/admin/company/${slug}/projects`}>← All Projects</Link><Link href={`/portal/${slug}/projects`}>Client View</Link></div>
 <header className="project-workspace-header"><div><span className="admin-eyebrow">{project.company?.name}</span><input className="project-title-input" value={project.title} onChange={e=>setProject({...project,title:e.target.value})}/><p>Created {new Date(project.createdAt).toLocaleDateString()}</p></div><div><select value={project.status} onChange={e=>{setProject({...project,status:e.target.value});save({status:e.target.value})}}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><button className="admin-primary-button" onClick={()=>save(project)}>Save Project</button></div></header>{message&&<p>{message}</p>}
 <div className="project-workspace-grid"><section className="project-panel project-overview"><h2>Overview</h2><label>Description<textarea value={project.description||""} onChange={e=>setProject({...project,description:e.target.value})}/></label><div className="project-fields"><label>Priority<select value={project.priority} onChange={e=>setProject({...project,priority:e.target.value})}><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></label><label>Assigned To<input value={project.assignedTo||""} onChange={e=>setProject({...project,assignedTo:e.target.value})}/></label><label>Start Date<input type="date" value={project.startDate?.slice(0,10)||""} onChange={e=>setProject({...project,startDate:e.target.value})}/></label><label>Due Date<input type="date" value={project.dueDate?.slice(0,10)||""} onChange={e=>setProject({...project,dueDate:e.target.value})}/></label><label>Budget<input type="number" value={project.budget??""} onChange={e=>setProject({...project,budget:e.target.value})}/></label><label>Internal Cost<input type="number" value={project.internalCost??""} onChange={e=>setProject({...project,internalCost:e.target.value})}/></label></div><label className="project-checkbox"><input type="checkbox" checked={project.clientVisible} onChange={e=>setProject({...project,clientVisible:e.target.checked})}/> Visible in client portal</label></section>
 <section className="project-panel"><h2>Tasks</h2><form className="project-inline-form" onSubmit={addTask}><input placeholder="Add a task" value={task} onChange={e=>setTask(e.target.value)}/><button>Add</button></form><div className="task-list">{project.tasks.map((t:any)=><article key={t.id}><button className={`task-check ${t.status==="done"?"done":""}`} onClick={()=>updateTask(t.id,t.status==="done"?"todo":"done")}>{t.status==="done"?"✓":""}</button><div><strong>{t.title}</strong><span>{t.assignedTo||"Unassigned"}</span></div><select value={t.status} onChange={e=>updateTask(t.id,e.target.value)}><option value="todo">To do</option><option value="in_progress">In progress</option><option value="review">Review</option><option value="done">Done</option></select></article>)}</div></section>
 <section className="project-panel"><h2>Notes</h2><form onSubmit={addNote}><textarea placeholder="Add project note" value={note} onChange={e=>setNote(e.target.value)}/><div className="project-inline-form"><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="internal">Internal</option><option value="client">Client visible</option></select><button>Add Note</button></div></form>{project.notes.map((n:any)=><article className="project-note" key={n.id}><span>{n.visibility}</span><p>{n.body}</p><small>{n.author} · {new Date(n.createdAt).toLocaleString()}</small></article>)}</section>
 <section className="project-panel"><h2>Activity</h2><div className="activity-list">{project.activities.map((a:any)=><article key={a.id}><i/><div><strong>{a.message}</strong><span>{new Date(a.createdAt).toLocaleString()}</span></div></article>)}</div></section></div>
 <button className="admin-danger-button" onClick={remove}>Delete Project</button></section></main>;
}