"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { getIntakeForm, type IntakeDefinition, type IntakeField } from "@/lib/intake-forms";

type PortalCompany={name:string;shortName:string;logo?:string|null;primaryColor:string;secondaryColor:string};
type PortfolioOption={id:number;name:string;address?:string|null;type:string};
type PortfolioMode="new"|"existing";

function initialValues(fields:IntakeField[]){return fields.reduce<Record<string,string|boolean>>((values,field)=>{values[field.key]=field.type==="checkbox"?false:field.key==="priority"?"normal":"";return values;},{});}

export default function ProjectRequestPage(){
 const params=useParams();const router=useRouter();const companySlug=Array.isArray(params?.company)?params.company[0]:params?.company;const serviceSlug=Array.isArray(params?.service)?params.service[0]:params?.service;const fallback=getIntakeForm(serviceSlug);
 const[definition,setDefinition]=useState<IntakeDefinition>(fallback);const[availableServices,setAvailableServices]=useState<IntakeDefinition[]>([]);const[portfolios,setPortfolios]=useState<PortfolioOption[]>([]);const[mode,setMode]=useState<PortfolioMode>("new");const[portfolioId,setPortfolioId]=useState("");const[portfolioName,setPortfolioName]=useState("");const[locationName,setLocationName]=useState("");const[company,setCompany]=useState<PortalCompany|null>(null);const[brandLoading,setBrandLoading]=useState(true);const[saving,setSaving]=useState(false);const[toast,setToast]=useState<{type:"success"|"error";message:string}|null>(null);const[submitted,setSubmitted]=useState(false);const[form,setForm]=useState<Record<string,string|boolean>>(()=>initialValues(fallback.fields));
 useEffect(()=>{if(!companySlug)return;const savedSlug=window.localStorage.getItem("upz_company_slug");if(savedSlug!==companySlug){router.push("/login");return;}const query=new URLSearchParams(window.location.search);const requestedPortfolio=query.get("engagementId")||query.get("portfolioId")||"";setPortfolioId(requestedPortfolio);setMode(requestedPortfolio?"existing":"new");setPortfolioName(query.get("engagementName")||query.get("portfolioName")||"");setLocationName(query.get("location")||"");setBrandLoading(true);Promise.all([fetch(`/api/portal/companies/${companySlug}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error("Unable to load company branding");return data;}),fetch(`/api/portal/companies/${companySlug}/services`,{cache:"no-store"}).then(response=>response.ok?response.json():[]),fetch(`/api/portal/companies/${companySlug}/projects`,{cache:"no-store"}).then(response=>response.ok?response.json():[])]).then(([companyData,serviceData,portfolioData])=>{setCompany(companyData);const list=Array.isArray(serviceData)?serviceData:[];setAvailableServices(list);setPortfolios(Array.isArray(portfolioData)?portfolioData.map((item:PortfolioOption)=>({id:item.id,name:item.name,address:item.address,type:item.type})):[]);const selected=list.find((item:IntakeDefinition)=>item.slug===serviceSlug)||getIntakeForm(serviceSlug);setDefinition(selected);setForm(initialValues(selected.fields));}).catch(()=>setCompany(null)).finally(()=>setBrandLoading(false));},[companySlug,serviceSlug,router]);
 useEffect(()=>{setSubmitted(false);setToast(null);},[definition]);useEffect(()=>{if(!toast)return;const timer=window.setTimeout(()=>setToast(null),5000);return()=>window.clearTimeout(timer);},[toast]);useEffect(()=>{if(submitted)window.scrollTo({top:0,left:0,behavior:"auto"});},[submitted]);
 function updateForm(field:string,value:string|boolean){setForm(current=>({...current,[field]:value}));}function selectMode(next:PortfolioMode){setMode(next);if(next==="new")setPortfolioId("");else setPortfolioName("");}
 async function submitRequest(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!companySlug)return;if(mode==="new"&&!portfolioName.trim()){setToast({type:"error",message:"Add a project, property, or campaign name."});return;}if(mode==="existing"&&!portfolioId){setToast({type:"error",message:"Choose an existing project or property."});return;}if(!locationName.trim()){setToast({type:"error",message:"Add the space, location, or asset for this request."});return;}setSaving(true);setToast(null);try{const selectedPortfolio=portfolios.find(item=>String(item.id)===portfolioId);const resolvedPortfolio=mode==="existing"?selectedPortfolio?.name||"Existing project":portfolioName.trim();const propertyAddress=String(form.propertyAddress||selectedPortfolio?.address||"").trim();const workOrderTitle=`${locationName.trim()} · ${definition.name}`;const response=await fetch(`/api/portal/companies/${companySlug}/requests`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({service:definition.name,serviceSlug:definition.slug,engagementId:mode==="existing"?portfolioId:undefined,engagementName:resolvedPortfolio,portfolioName:resolvedPortfolio,locationName:locationName.trim(),workOrderTitle,propertyAddress,priority:form.priority||"normal",answers:form})});const data=await response.json();if(!response.ok)throw new Error(data?.error||"Unable to submit request");setSubmitted(true);setToast({type:"success",message:`${workOrderTitle} was submitted for review.`});}catch(error:unknown){setToast({type:"error",message:error instanceof Error?error.message:"Unable to submit request"});}finally{setSaving(false);}}
 function renderField(field:IntakeField){const value=form[field.key]??"";const className=field.wide?"portal-request-wide":undefined;if(field.type==="textarea")return <label key={field.key} className={className}>{field.label}<textarea value={String(value)} onChange={event=>updateForm(field.key,event.target.value)} placeholder={field.placeholder} required={field.required}/></label>;if(field.type==="select")return <label key={field.key} className={className}>{field.label}<select value={String(value)} onChange={event=>updateForm(field.key,event.target.value)} required={field.required}><option value="">Select an option</option>{field.options?.map(option=><option key={option} value={option.toLowerCase()}>{option}</option>)}</select></label>;if(field.type==="checkbox")return <label key={field.key} className={`portal-request-checkbox ${className||""}`}><input type="checkbox" checked={Boolean(value)} onChange={event=>updateForm(field.key,event.target.checked)}/><span>{field.label}</span></label>;return <label key={field.key} className={className}>{field.label}<input type={field.type} value={String(value)} onChange={event=>updateForm(field.key,event.target.value)} placeholder={field.placeholder} required={field.required}/></label>;}
 if(brandLoading)return <main className="portal-page portal-request-page request-brand-loading" aria-busy="true"><div className="request-brand-loading-mark"/></main>;if(!company)return <main className="portal-page portal-request-page"><section className="portal-request-success"><span>Portal unavailable</span><h1>Unable to load branding.</h1><p>Please return to the portal and try again.</p><div className="portal-request-success-actions"><Link href={`/portal/${companySlug}`}>Return to Portal</Link></div></section></main>;
 const brandStyle={"--company-primary":company.primaryColor,"--company-secondary":company.secondaryColor} as React.CSSProperties;
 if(submitted)return <main className="portal-page portal-request-page branded-request-page" style={brandStyle}><nav className="portal-request-nav"><Link href={`/portal/${companySlug}`}>Project Home</Link><Link href={`/portal/${companySlug}/projects`}>Projects &amp; Requests</Link><Link className="active" href={`/portal/${companySlug}/request/general`}>New Request</Link></nav>{toast&&<div className={`upz-toast ${toast.type}`} role="status"><strong>✓</strong><span>{toast.message}</span></div>}<section className="portal-request-success">{company.logo&&<img className="request-company-logo" src={company.logo} alt={`${company.name} logo`}/>}<span>Request submitted</span><h1>Your request is under review.</h1><p>Once approved, it will appear under the selected project as an active work order with its own stages, manager, messages, and deliverables.</p><div className="portal-request-success-actions"><Link href={`/portal/${companySlug}`}>Return to Portal</Link><Link href={`/portal/${companySlug}/projects`}>View Projects &amp; Requests</Link></div></section></main>;
 return <main className="portal-page portal-request-page branded-request-page" style={brandStyle}><nav className="portal-request-nav"><Link href={`/portal/${companySlug}`}>← Portal Home</Link><Link href={`/portal/${companySlug}/projects`}>Projects &amp; Requests</Link><Link className="active" href={`/portal/${companySlug}/request/general`}>New Request</Link></nav>{toast&&<div className={`upz-toast ${toast.type}`} role="alert"><strong>{toast.type==="success"?"✓":"!"}</strong><span>{toast.message}</span></div>}<section className="portal-request-wrap"><div className="portal-request-intro">{company.logo&&<img className="request-company-logo" src={company.logo} alt={`${company.name} logo`}/>}<span>{company.shortName} · New Request</span><h1>{definition.name}</h1><p>{definition.description}</p><nav className="portal-project-type-list" aria-label="Services">{availableServices.map(item=><Link key={item.slug} className={item.slug===definition.slug?"active":""} href={`/portal/${companySlug}/request/${item.slug}`}>{item.name}</Link>)}</nav></div><form className="portal-request-form" onSubmit={submitRequest}><div className="portal-request-form-heading portal-request-wide"><span>{company.name}</span><h2>Create a request</h2><p>Choose the project or property first, then identify the specific space, location, or asset receiving this service.</p></div><div className="request-mode-tabs portal-request-wide"><button type="button" className={mode==="new"?"active":""} onClick={()=>selectMode("new")}>New Project</button><button type="button" className={mode==="existing"?"active":""} onClick={()=>selectMode("existing")}>Existing Project</button></div>{mode==="new"?<label className="portal-request-wide">Project / Property Name<input value={portfolioName} onChange={event=>setPortfolioName(event.target.value)} placeholder="Example: 123 Fifth Avenue" required/></label>:<label className="portal-request-wide">Choose Project / Property<select value={portfolioId} onChange={event=>setPortfolioId(event.target.value)} required><option value="">Select an existing project</option>{portfolios.map(item=><option key={item.id} value={item.id}>{item.name}{item.address?` — ${item.address}`:""}</option>)}</select></label>}<label className="portal-request-wide">Space / Location / Asset<input value={locationName} onChange={event=>setLocationName(event.target.value)} placeholder="Example: Space B, Lobby, Exterior, Suite 1200" required/><small>The approved work order will be named “{locationName.trim()||"Space B"} · {definition.name}”.</small></label>{definition.fields.map(renderField)}<div className="portal-request-actions"><button type="submit" disabled={saving}>{saving?"Submitting Request...":"Submit Request for Review"}</button></div></form></section></main>;
}
