"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { getIntakeForm, type IntakeDefinition, type IntakeField } from "@/lib/intake-forms";

type PortalCompany={name:string;shortName:string;logo?:string|null;primaryColor:string;secondaryColor:string};
type EngagementOption={id:number;name:string;address?:string|null;type:string};
type RequestMode="new"|"existing";

function initialValues(fields:IntakeField[]){return fields.reduce<Record<string,string|boolean>>((values,field)=>{values[field.key]=field.type==="checkbox"?false:field.key==="priority"?"normal":"";return values;},{});}

export default function ProjectRequestPage(){
 const params=useParams();const router=useRouter();const companySlug=Array.isArray(params?.company)?params.company[0]:params?.company;const serviceSlug=Array.isArray(params?.service)?params.service[0]:params?.service;const fallback=getIntakeForm(serviceSlug);
 const [definition,setDefinition]=useState<IntakeDefinition>(fallback);const [availableServices,setAvailableServices]=useState<IntakeDefinition[]>([]);const [engagements,setEngagements]=useState<EngagementOption[]>([]);const [mode,setMode]=useState<RequestMode>("new");const [engagementId,setEngagementId]=useState("");const [projectName,setProjectName]=useState("");const [company,setCompany]=useState<PortalCompany|null>(null);const [brandLoading,setBrandLoading]=useState(true);const [saving,setSaving]=useState(false);const [toast,setToast]=useState<{type:"success"|"error";message:string}|null>(null);const [submitted,setSubmitted]=useState(false);const [form,setForm]=useState<Record<string,string|boolean>>(()=>initialValues(fallback.fields));
 useEffect(()=>{if(!companySlug)return;const savedSlug=window.localStorage.getItem("upz_company_slug");if(savedSlug!==companySlug){router.push("/login");return;}const query=new URLSearchParams(window.location.search);const requestedEngagement=query.get("engagementId")||"";setEngagementId(requestedEngagement);setMode(requestedEngagement?"existing":"new");setProjectName(query.get("engagementName")||"");setBrandLoading(true);Promise.all([fetch(`/api/portal/companies/${companySlug}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error("Unable to load company branding");return data;}),fetch(`/api/portal/companies/${companySlug}/services`,{cache:"no-store"}).then(response=>response.ok?response.json():[]),fetch(`/api/portal/companies/${companySlug}/projects`,{cache:"no-store"}).then(response=>response.ok?response.json():[])]).then(([companyData,serviceData,engagementData])=>{setCompany(companyData);const list=Array.isArray(serviceData)?serviceData:[];setAvailableServices(list);setEngagements(Array.isArray(engagementData)?engagementData.map((item:EngagementOption)=>({id:item.id,name:item.name,address:item.address,type:item.type})):[]);const selected=list.find((item:IntakeDefinition)=>item.slug===serviceSlug)||getIntakeForm(serviceSlug);setDefinition(selected);setForm(initialValues(selected.fields));}).catch(()=>setCompany(null)).finally(()=>setBrandLoading(false));},[companySlug,serviceSlug,router]);
 useEffect(()=>{setSubmitted(false);setToast(null);},[definition]);useEffect(()=>{if(!toast)return;const timer=window.setTimeout(()=>setToast(null),5000);return()=>window.clearTimeout(timer);},[toast]);
 function updateForm(field:string,value:string|boolean){setForm(current=>({...current,[field]:value}));}function selectMode(next:RequestMode){setMode(next);if(next==="new")setEngagementId("");else setProjectName("");}
 async function submitRequest(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!companySlug)return;if(mode==="new"&&!projectName.trim()){setToast({type:"error",message:"Add a project or campaign name."});return;}if(mode==="existing"&&!engagementId){setToast({type:"error",message:"Choose an existing project or campaign."});return;}setSaving(true);setToast(null);try{const selectedEngagement=engagements.find(item=>String(item.id)===engagementId);const resolvedName=mode==="existing"?selectedEngagement?.name||"Existing project":projectName.trim();const propertyAddress=String(form.propertyAddress||"").trim();const response=await fetch(`/api/portal/companies/${companySlug}/requests`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({service:definition.name,serviceSlug:definition.slug,engagementId:mode==="existing"?engagementId:undefined,engagementName:resolvedName,workOrderTitle:definition.name,propertyAddress,priority:form.priority||"normal",answers:form})});const data=await response.json();if(!response.ok)throw new Error(data?.error||"Unable to submit service request");setSubmitted(true);setToast({type:"success",message:`${definition.name} was submitted for review.`});}catch(error:unknown){setToast({type:"error",message:error instanceof Error?error.message:"Unable to submit service request"});}finally{setSaving(false);}}
 function renderField(field:IntakeField){const value=form[field.key]??"";const className=field.wide?"portal-request-wide":undefined;if(field.type==="textarea")return <label key={field.key} className={className}>{field.label}<textarea value={String(value)} onChange={event=>updateForm(field.key,event.target.value)} placeholder={field.placeholder} required={field.required}/></label>;if(field.type==="select")return <label key={field.key} className={className}>{field.label}<select value={String(value)} onChange={event=>updateForm(field.key,event.target.value)} required={field.required}><option value="">Select an option</option>{field.options?.map(option=><option key={option} value={option.toLowerCase()}>{option}</option>)}</select></label>;if(field.type==="checkbox")return <label key={field.key} className={`portal-request-checkbox ${className||""}`}><input type="checkbox" checked={Boolean(value)} onChange={event=>updateForm(field.key,event.target.checked)}/><span>{field.label}</span></label>;return <label key={field.key} className={className}>{field.label}<input type={field.type} value={String(value)} onChange={event=>updateForm(field.key,event.target.value)} placeholder={field.placeholder} required={field.required}/></label>;}
 if(brandLoading)return <main className="portal-page portal-request-page request-brand-loading" aria-busy="true"><div className="request-brand-loading-mark"/></main>;if(!company)return <main className="portal-page portal-request-page"><section className="portal-request-success"><span>Portal unavailable</span><h1>Unable to load branding.</h1><p>Please return to the portal and try again.</p><div className="portal-request-success-actions"><Link href={`/portal/${companySlug}`}>Return to Portal</Link></div></section></main>;
 const brandStyle={"--company-primary":company.primaryColor,"--company-secondary":company.secondaryColor} as React.CSSProperties;
 if(submitted)return <main className="portal-page portal-request-page branded-request-page" style={brandStyle}>{toast&&<div className={`upz-toast ${toast.type}`} role="status"><strong>✓</strong><span>{toast.message}</span></div>}<section className="portal-request-success">{company.logo&&<img className="request-company-logo" src={company.logo} alt={`${company.name} logo`}/>}<span>Request submitted</span><h1>Your request is under review.</h1><p>You can track it in Projects &amp; Campaigns with a Pending status. Once approved, the project and its production updates will appear there. If it is declined or cancelled, the status and reason will also be shown.</p><div className="portal-request-success-actions"><Link href={`/portal/${companySlug}`}>Return to Portal</Link><Link href={`/portal/${companySlug}/projects`}>View Project Updates</Link></div></section></main>;
 return <main className="portal-page portal-request-page branded-request-page" style={brandStyle}>{toast&&<div className={`upz-toast ${toast.type}`} role="alert"><strong>{toast.type==="success"?"✓":"!"}</strong><span>{toast.message}</span></div>}<section className="portal-request-wrap"><div className="portal-request-intro">{company.logo&&<img className="request-company-logo" src={company.logo} alt={`${company.name} logo`}/>}<span>{company.shortName} · Submit a Request</span><h1>{definition.name}</h1><p>{definition.description}</p><nav className="portal-project-type-list" aria-label="Project types">{availableServices.map(item=><Link key={item.slug} className={item.slug===definition.slug?"active":""} href={`/portal/${companySlug}/request/${item.slug}`}>{item.name}</Link>)}</nav></div><form className="portal-request-form" onSubmit={submitRequest}><div className="portal-request-form-heading portal-request-wide"><span>{company.name}</span><h2>{definition.name} request</h2><p>First choose whether this belongs to a new or existing project. Then provide only the essential service details.</p></div><div className="request-mode-tabs portal-request-wide"><button type="button" className={mode==="new"?"active":""} onClick={()=>selectMode("new")}>New Project</button><button type="button" className={mode==="existing"?"active":""} onClick={()=>selectMode("existing")}>Existing Project</button></div>{mode==="new"?<label className="portal-request-wide">Project or Campaign Name<input value={projectName} onChange={event=>setProjectName(event.target.value)} placeholder="Example: 645 Madison Avenue" required/></label>:<label className="portal-request-wide">Choose Project or Campaign<select value={engagementId} onChange={event=>setEngagementId(event.target.value)} required><option value="">Select an existing project</option>{engagements.map(item=><option key={item.id} value={item.id}>{item.name}{item.address?` — ${item.address}`:""}</option>)}</select></label>}{definition.fields.map(renderField)}<div className="portal-request-actions"><button type="submit" disabled={saving}>{saving?"Submitting Request...":"Submit for Review"}</button></div></form></section></main>;
}