"use client";

import { useEffect,useMemo,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { getWorkflowTemplate,type WorkflowStep } from "@/lib/workflow-templates";
import RequestDetails from "@/components/RequestDetails";
import { AdminButton,AdminCard,AdminField,AdminFormGrid,AdminHeader,AdminPage,AdminSection,AdminSectionHeader } from "@/components/admin/AdminUI";

type RequestDetail={id:number;type:string;title:string;description?:string|null;priority:string;status:string;createdAt:string;company:{name:string;shortName:string;slug:string;logo?:string|null;primaryColor:string};project?:{id:number}|null};
type Member={id:number;name:string;role:string};type ParentProject={id:number;name:string;address?:string|null;type:string;company?:{slug:string}};
type ApprovalStage=WorkflowStep&{id:string;assignedTo?:string;requiresFiles?:boolean};type SavedTemplate={id:number;slug:string;name:string;stages:WorkflowStep[]};
type RequestContext={engagementId?:number|null;engagementName?:string;portfolioName?:string;propertyAddress?:string|null;locationName?:string;service?:string};
function parseRequest(value?:string|null){const source=value||"",marker="__UPZ_CONTEXT__",index=source.lastIndexOf(marker);let context:RequestContext={};if(index>=0)try{context=JSON.parse(source.slice(index+marker.length).trim())}catch{}return{description:(index>=0?source.slice(0,index):source).trim()||"No additional description provided.",context};}
function decisionReason(value?:string|null){const marker="__UPZ_DECISION__",source=value||"",index=source.lastIndexOf(marker);if(index<0)return"";try{return JSON.parse(source.slice(index+marker.length).trim()).reason||""}catch{return""}}
const normalize=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-");
function matchingTemplate(templates:SavedTemplate[],service:string){const key=normalize(service);return templates.find(template=>template.slug===key)||templates.find(template=>key.includes(template.slug)||template.slug.includes(key))||templates.find(template=>key.includes("photo")&&template.slug.includes("photo"))||templates.find(template=>key.includes("web")&&template.slug.includes("web"));}
function makeStages(service:string,saved:SavedTemplate[]=[]):ApprovalStage[]{const source=matchingTemplate(saved,service)?.stages||getWorkflowTemplate(service);return source.map((stage,index)=>({...stage,id:`${Date.now()}-${index}`,assignedTo:"",requiresFiles:/final delivery|delivery|upload/i.test(stage.title)}));}
function stageDate(stage:ApprovalStage,index:number,stages:ApprovalStage[],start:string,end:string){if(!start||!end)return"Set overall dates";const a=new Date(`${start}T12:00:00`),b=new Date(`${end}T12:00:00`),days=Math.max(0,Math.round((b.getTime()-a.getTime())/86400000)),max=Math.max(1,...stages.map((item,i)=>Number(item.durationDays??i))),offset=Math.max(0,Math.min(days,Math.round(Number(stage.durationDays??index)/max*days)));a.setDate(a.getDate()+offset);return a.toLocaleDateString();}

export default function RequestReviewPage(){
 const params=useParams(),router=useRouter(),id=Array.isArray(params?.id)?params.id[0]:params?.id;
 const[item,setItem]=useState<RequestDetail|null>(null),[team,setTeam]=useState<Member[]>([]),[parents,setParents]=useState<ParentProject[]>([]),[stages,setStages]=useState<ApprovalStage[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[working,setWorking]=useState<"approve"|"decline"|null>(null),[manager,setManager]=useState(""),[startDate,setStartDate]=useState(""),[dueDate,setDueDate]=useState(""),[declineReason,setDeclineReason]=useState(""),[projectMode,setProjectMode]=useState<"existing"|"new">("new"),[projectId,setProjectId]=useState(""),[projectName,setProjectName]=useState(""),[propertyAddress,setPropertyAddress]=useState(""),[locationName,setLocationName]=useState(""),[workOrderTitle,setWorkOrderTitle]=useState("");
 const parsed=useMemo(()=>parseRequest(item?.description),[item?.description]);
 const selectedParent=parents.find(p=>String(p.id)===projectId);const resolvedProjectName=projectMode==="existing"?selectedParent?.name||"Selected project":projectName.trim()||"Project";
 useEffect(()=>{if(!id)return;Promise.all([fetch(`/api/admin/requests/${id}`,{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Unable to load request");return r.json()}),fetch("/api/admin/operations",{cache:"no-store"}).then(r=>r.ok?r.json():{team:[],engagements:[]}),fetch("/api/admin/workflow-templates",{cache:"no-store"}).then(r=>r.ok?r.json():[])]).then(([requestData,operations,templates])=>{const detail=parseRequest(requestData.description);setItem(requestData);setTeam(Array.isArray(operations.team)?operations.team:[]);setParents((Array.isArray(operations.engagements)?operations.engagements:[]).filter((entry:ParentProject)=>!entry.company||entry.company.slug===requestData.company.slug));setStages(makeStages(requestData.type||requestData.title,Array.isArray(templates)?templates:[]));setDeclineReason(decisionReason(requestData.description));const requested=detail.context.engagementId?String(detail.context.engagementId):"";setProjectId(requested);setProjectMode(requested?"existing":"new");setProjectName(detail.context.portfolioName||detail.context.engagementName||"");setPropertyAddress(detail.context.propertyAddress||"");setLocationName(detail.context.locationName||requestData.title.split("·")[1]?.trim()||requestData.title.split("·")[0]?.trim()||"");setWorkOrderTitle(requestData.title)}).catch(e=>setMessage(e.message||"Unable to load request")).finally(()=>setLoading(false))},[id]);
 useEffect(()=>{if(!item)return;setWorkOrderTitle(`${resolvedProjectName} · ${locationName.trim()||"Location"} · ${item.type}`)},[resolvedProjectName,locationName,item]);
 const updateStage=(stageId:string,patch:Partial<ApprovalStage>)=>setStages(current=>current.map(stage=>stage.id===stageId?{...stage,...patch}:stage));
 function moveStage(index:number,direction:-1|1){setStages(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next})}
 function addStage(){setStages(current=>[...current,{id:`${Date.now()}-${current.length}`,title:"New stage",description:"",durationDays:current.length?Number(current.at(-1)?.durationDays||current.length-1)+1:0,clientVisible:true,assignedTo:"",requiresFiles:false}])}
 async function approve(){if(!item||working)return;if(projectMode==="existing"&&!projectId)return setMessage("Choose an existing project.");if(projectMode==="new"&&!projectName.trim())return setMessage("Add a project or property name.");if(!locationName.trim())return setMessage("Add the location.");if(!startDate||!dueDate)return setMessage("Set the overall project start and due dates before approval.");if(new Date(dueDate)<new Date(startDate))return setMessage("Due date must be on or after the start date.");setWorking("approve");setMessage("");try{const response=await fetch(`/api/admin/requests/${item.id}/convert`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:workOrderTitle.trim(),assignedTo:manager,startDate,dueDate,priority:item.priority,clientVisible:true,engagementId:projectMode==="existing"?Number(projectId):null,engagementName:resolvedProjectName,engagementType:propertyAddress?"property":"portfolio",propertyAddress:propertyAddress.trim()||selectedParent?.address||null,locationName:locationName.trim(),stages:stages.map(({title,description,durationDays,clientVisible,assignedTo,requiresFiles})=>({title,description,durationDays,clientVisible,assignedTo,requiresFiles}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to approve request");router.push(`/admin/project/${data.id}`)}catch(e:any){setMessage(e.message||"Unable to approve request");setWorking(null)}}
 async function decline(){if(!item||working||!declineReason.trim())return;setWorking("decline");const description=`${parsed.description}\n\n__UPZ_DECISION__${JSON.stringify({reason:declineReason.trim()})}`;const response=await fetch(`/api/admin/requests/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"declined",description})});if(response.ok){setMessage("Request declined. The client will see the reason.");setWorking(null)}else{setMessage("Unable to decline request");setWorking(null)}}
 if(loading)return <AdminPage><AdminSection><h1>Loading request...</h1></AdminSection></AdminPage>;if(!item)return <AdminPage><AdminSection><h1>Request not found</h1></AdminSection></AdminPage>;
 const decisionState=item.project?"approved":item.status==="declined"?"declined":"pending";
 return <AdminPage className="request-review-page request-setup-page"><AdminHeader eyebrow="Request Review" title={item.title} description={`${item.company.name} · ${item.type} · submitted ${new Date(item.createdAt).toLocaleString()}`} actions={<div className="request-header-brand" style={{borderColor:item.company.primaryColor}}><img src={item.company.logo||"/upz-logo.svg"} alt=""/><span>{item.company.shortName}</span></div>}/>
 {decisionState==="approved"?<AdminSection><AdminSectionHeader eyebrow="Work Order Created" title="This request is active"/><AdminButton href={`/admin/project/${item.project?.id}`}>Open Workspace</AdminButton></AdminSection>:decisionState==="declined"?<AdminSection><AdminSectionHeader eyebrow="Final Decision" title="Request declined"/><p>{declineReason}</p></AdminSection>:<>
 <section className="request-setup-grid"><AdminSection><AdminSectionHeader eyebrow="Client Intake" title="Request brief"/><div className="request-detail-badges"><b>{item.status}</b><em>{item.priority} priority</em></div><RequestDetails value={parsed.description}/></AdminSection><AdminSection><AdminSectionHeader eyebrow="Project Setup" title="Place this request"/><div className="request-mode-tabs"><button type="button" className={projectMode==="existing"?"active":""} onClick={()=>setProjectMode("existing")}>Existing Project</button><button type="button" className={projectMode==="new"?"active":""} onClick={()=>setProjectMode("new")}>New Project</button></div><AdminFormGrid>{projectMode==="existing"?<AdminField label="Project / Property" className="wide"><select value={projectId} onChange={e=>{setProjectId(e.target.value);const selected=parents.find(p=>String(p.id)===e.target.value);if(selected?.address)setPropertyAddress(selected.address)}}><option value="">Choose project</option>{parents.map(p=><option key={p.id} value={p.id}>{p.name}{p.address?` — ${p.address}`:""}</option>)}</select></AdminField>:<AdminField label="Project / Property Name" className="wide"><input value={projectName} onChange={e=>setProjectName(e.target.value)}/></AdminField>}<AdminField label="Property address" className="wide"><input value={propertyAddress} onChange={e=>setPropertyAddress(e.target.value)}/></AdminField><AdminField label="Space / Location"><input value={locationName} onChange={e=>setLocationName(e.target.value)}/></AdminField><AdminField label="Production title"><input value={workOrderTitle} onChange={e=>setWorkOrderTitle(e.target.value)}/></AdminField></AdminFormGrid></AdminSection></section>
 <AdminSection className="approval-schedule-panel"><AdminSectionHeader eyebrow="Ownership & Schedule" title="Overall work order plan"/><p>The overall dates define the full production window. Stage deadlines below are automatically distributed within this range and remain editable later.</p><AdminFormGrid><AdminField label="Project manager" className="wide"><select value={manager} onChange={e=>setManager(e.target.value)}><option value="">Unassigned</option>{team.map(member=><option key={member.id} value={member.name}>{member.name} — {member.role}</option>)}</select></AdminField><AdminField label="Start date"><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></AdminField><AdminField label="Final due date"><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></AdminField></AdminFormGrid><div className="request-setup-summary"><AdminCard variant="highlight"><span>Production window</span><strong>{startDate&&dueDate?`${startDate} → ${dueDate}`:"Dates required"}</strong></AdminCard><AdminCard variant="compact"><span>Project manager</span><strong>{manager||"Unassigned"}</strong></AdminCard></div></AdminSection>
 <AdminSection className="request-stage-builder"><AdminSectionHeader eyebrow="Workflow Builder" title="Stages, owners, and deadlines" actions={<><AdminButton variant="ghost" href="/admin/templates">Workflow Templates</AdminButton><AdminButton variant="outline" type="button" onClick={addStage}>Add Stage</AdminButton></>}/><p className="request-stage-intro">Assign specialist stages directly here. The project manager sees the full work order; each specialist sees only stages assigned to them.</p><div className="request-stage-list">{stages.map((stage,index)=><article className="request-stage-row approval-stage-card" key={stage.id}><div className="request-stage-number"><span>Stage</span><strong>{index+1}</strong><small>{stageDate(stage,index,stages,startDate,dueDate)}</small></div><div className="request-stage-fields"><AdminField label="Stage name" className="wide"><input value={stage.title} onChange={e=>updateStage(stage.id,{title:e.target.value})}/></AdminField><AdminField label="Instructions" className="wide"><textarea value={stage.description||""} onChange={e=>updateStage(stage.id,{description:e.target.value})}/></AdminField><AdminField label="Stage owner"><select value={stage.assignedTo||""} onChange={e=>updateStage(stage.id,{assignedTo:e.target.value})}><option value="">Use project manager</option>{team.map(member=><option key={member.id} value={member.name}>{member.name} — {member.role}</option>)}</select></AdminField><AdminField label="Template timing"><input type="number" min="0" value={stage.durationDays??index} onChange={e=>updateStage(stage.id,{durationDays:Number(e.target.value)})}/><small>Relative position inside the overall schedule.</small></AdminField><div className="approval-stage-toggles"><label><input type="checkbox" checked={stage.clientVisible!==false} onChange={e=>updateStage(stage.id,{clientVisible:e.target.checked})}/> Client visible</label><label><input type="checkbox" checked={Boolean(stage.requiresFiles)} onChange={e=>updateStage(stage.id,{requiresFiles:e.target.checked})}/> Files required to complete</label></div></div><div className="request-stage-actions"><AdminButton variant="ghost" type="button" onClick={()=>moveStage(index,-1)} disabled={index===0}>Up</AdminButton><AdminButton variant="ghost" type="button" onClick={()=>moveStage(index,1)} disabled={index===stages.length-1}>Down</AdminButton><AdminButton variant="danger" type="button" onClick={()=>setStages(current=>current.filter(entry=>entry.id!==stage.id))}>Remove</AdminButton></div></article>)}</div></AdminSection>
 <section className="request-final-actions"><AdminSection className="request-approval-panel"><AdminSectionHeader eyebrow="Ready to Launch" title="Approve request"/><p>Create <strong>{workOrderTitle}</strong> with {stages.length} scheduled stages.</p><AdminButton type="button" onClick={approve} disabled={Boolean(working)}>{working==="approve"?"Creating Work Order...":"Approve & Launch Work Order"}</AdminButton></AdminSection><AdminSection className="request-decline-box"><AdminSectionHeader eyebrow="Alternative" title="Decline request"/><AdminField label="Client-visible reason"><textarea value={declineReason} onChange={e=>setDeclineReason(e.target.value)}/></AdminField><AdminButton variant="danger" type="button" onClick={decline} disabled={Boolean(working)||!declineReason.trim()}>Decline Request</AdminButton></AdminSection></section>{message&&<p className={message.startsWith("Request declined")?"admin-inline-success":"admin-error"}>{message}</p>}</>}
 </AdminPage>;
}