"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { formatPrice } from "@/lib/catalog";
import type { IntakeDefinition } from "@/lib/intake-forms";
import { useCartStore, type CartItem } from "@/store/cart-store";

type PortalCompany={id:string;slug:string;name:string;shortName:string;logo:string;primaryColor:string;secondaryColor:string;brandTextColor?:string;heroTitle:string;heroText:string;modules:string[];featuredActions:Array<{title:string;description:string;href:string}>};
type Collection={id:number;name:string;slug:string;description?:string|null;heroImage?:string|null;active?:boolean};
type CatalogItem={id:number;title:string;description?:string|null;itemType:string;sourceVendor?:string|null;thumbnail?:string|null;price?:number|null;active:boolean;featured:boolean;sortOrder:number;collection?:Collection|null;product?:{id:number}|null};
type EngagementSummary={id:number;name:string;type:string;address?:string|null;status:string;currentStatus?:string;progress:number;activeWorkOrders:number;updatedAt:string};
type PackageSummary={id:number;title:string;description?:string|null;featured:boolean;items?:unknown[]};

function getItemImage(item:CatalogItem){return item.thumbnail||"/placeholder.png";}function getItemLabel(item:CatalogItem){if(item.sourceVendor==="printful")return"Merchandise";if(item.itemType==="service")return"Service";if(item.itemType==="digital")return"Digital";if(item.itemType==="asset")return"Asset";return"Catalog Item";}function buildCartItem(item:CatalogItem,company:PortalCompany):CartItem{return{id:`catalog-${item.id}`,productId:item.product?.id?String(item.product.id):undefined,name:`${company.shortName} ${item.title}`,image:getItemImage(item),price:Number(item.price||0),quantity:1,companySlug:company.slug,companyName:company.name};}function slugLabel(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function CatalogCard({item,company,addItem}:{item:CatalogItem;company:PortalCompany;addItem:(item:CartItem)=>void}){const productHref=item.product?.id?`/portal/${company.slug}/product/${item.product.id}`:null;const content=<><div className="portal-product-card-image"><img src={getItemImage(item)} alt={item.title}/></div><div className="portal-product-card-body"><span>{getItemLabel(item)} · {item.collection?.name||"Catalog"}</span><h3>{company.shortName} {item.title}</h3><strong>{formatPrice(item.price)}</strong>{item.description&&<p>{item.description}</p>}<div className="portal-product-card-action">{productHref?"View Product":"Add to Cart"}<b>→</b></div></div></>;if(productHref)return <Link href={productHref} className="portal-product-card portal-product-card-link">{content}</Link>;return <article className="portal-product-card" onClick={()=>addItem(buildCartItem(item,company))} role="button" tabIndex={0}>{content}</article>;}
function ServiceCard({service,company}:{service:IntakeDefinition;company:PortalCompany}){return <Link href={`/portal/${company.slug}/request/${service.slug}`} className="portal-premium-service-card"><div className="portal-service-card-image"><img src={service.imageUrl||"/service-placeholders/general.svg"} alt=""/></div><div className="portal-service-card-copy"><span>Creative Service</span><h3>{service.name}</h3><p>{service.description}</p><strong>Start request <b>→</b></strong></div></Link>;}

export default function CompanyPortalPage(){
 const params=useParams();const router=useRouter();const slug=Array.isArray(params?.company)?params.company[0]:params?.company;const [company,setCompany]=useState<PortalCompany|null>(null);const [companyLoading,setCompanyLoading]=useState(true);const [companyError,setCompanyError]=useState("");const [catalogItems,setCatalogItems]=useState<CatalogItem[]>([]);const [engagements,setEngagements]=useState<EngagementSummary[]>([]);const [packages,setPackages]=useState<PackageSummary[]>([]);const [loading,setLoading]=useState(true);const [services,setServices]=useState<IntakeDefinition[]>([]);const [merchFilter,setMerchFilter]=useState("all");const addItem=useCartStore(state=>state.addItem);
 useEffect(()=>{if(!slug)return;const savedSlug=window.localStorage.getItem("upz_company_slug");if(savedSlug!==slug){router.push("/login");return;}setCompanyLoading(true);setCompanyError("");fetch(`/api/portal/companies/${slug}`).then(res=>{if(!res.ok)throw new Error("Portal not found");return res.json();}).then(setCompany).catch(err=>setCompanyError(err?.message||"Portal not found")).finally(()=>setCompanyLoading(false));},[slug,router]);
 useEffect(()=>{if(!company)return;setLoading(true);Promise.all([fetch(`/api/portal/companies/${company.slug}/catalog-items`).then(res=>{if(!res.ok)throw new Error("Unable to load catalog");return res.json();}),fetch(`/api/portal/companies/${company.slug}/projects`,{cache:"no-store"}).then(res=>res.ok?res.json():[]),fetch(`/api/portal/companies/${company.slug}/packages`).then(res=>res.ok?res.json():[]),fetch(`/api/portal/companies/${company.slug}/services`,{cache:"no-store"}).then(res=>res.ok?res.json():[])]).then(([catalog,projectData,packageData,serviceData])=>{setCatalogItems(Array.isArray(catalog)?catalog:[]);setEngagements(Array.isArray(projectData)?projectData:[]);setPackages(Array.isArray(packageData)?packageData:[]);setServices(Array.isArray(serviceData)?serviceData:[]);}).catch(()=>{setCatalogItems([]);setEngagements([]);setPackages([]);setServices([]);}).finally(()=>setLoading(false));},[company]);
 const merchandiseItems=useMemo(()=>catalogItems.filter(item=>item.itemType==="product"||item.sourceVendor==="printful"),[catalogItems]);const digitalItems=useMemo(()=>catalogItems.filter(item=>["digital","asset","custom"].includes(item.itemType)),[catalogItems]);const activeEngagements=useMemo(()=>engagements.filter(item=>!["complete","completed","archived","cancelled"].includes(item.status.toLowerCase())).slice(0,6),[engagements]);const featuredPackages=useMemo(()=>packages.filter(item=>item.featured).slice(0,3),[packages]);const groupedMerchandise=useMemo(()=>{const groups=new Map<string,{name:string;slug:string;items:CatalogItem[]}>();merchandiseItems.forEach(item=>{const name=item.collection?.name||"Merchandise";const groupSlug=item.collection?.slug||slugLabel(name);if(!groups.has(groupSlug))groups.set(groupSlug,{name,slug:groupSlug,items:[]});groups.get(groupSlug)?.items.push(item);});return Array.from(groups.values()).sort((a,b)=>a.name.localeCompare(b.name));},[merchandiseItems]);const visibleMerchandise=useMemo(()=>merchFilter==="all"?merchandiseItems:merchandiseItems.filter(item=>(item.collection?.slug||slugLabel(item.collection?.name||"Merchandise"))===merchFilter),[merchandiseItems,merchFilter]);
 if(companyLoading)return <main className="portal-page"><section className="portal-simple-state"><h1>Loading portal...</h1></section></main>;if(companyError||!company)return <main className="portal-page"><section className="portal-simple-state"><h1>Portal not found</h1><Link href="/login">Back to login</Link></section></main>;
 return <main className="portal-page" style={{"--company-primary":company.primaryColor,"--company-secondary":company.secondaryColor,"--company-on-primary":company.brandTextColor||company.secondaryColor||"#fff"} as React.CSSProperties}>
 <section className="portal-hero"><div className="upz-wrap portal-hero-inner"><div><div className="portal-eyebrow">Private Company Portal</div><h1>{company.heroTitle}</h1><p>{company.heroText}</p><div className="portal-actions"><Link href={`/portal/${company.slug}/projects`}>Active Projects</Link><a href="#services">Services</a><Link href={`/portal/${company.slug}/packages`}>Packages</Link><a href="#brand-assets">Brand Assets</a></div></div><div className="portal-brand-card"><img src={company.logo||"/upz-logo.svg"} alt={`${company.name} logo`}/><h2>{company.name}</h2><p>Approved creative services, projects, packages, merchandise, and brand resources.</p></div></div></section>
 <section className="portal-modules"><div className="upz-wrap portal-module-grid">{[{label:"Active Projects",href:`/portal/${company.slug}/projects`},...services.slice(0,5).map(service=>({label:service.name,href:`/portal/${company.slug}/request/${service.slug}`})),{label:"Packages",href:`/portal/${company.slug}/packages`},{label:"Brand Assets",href:"#brand-assets"}].map(module=><Link key={`${module.label}-${module.href}`} href={module.href} className="portal-module-card"><span>{module.label}</span></Link>)}</div></section>
 <section id="requests" className="portal-section portal-request-dashboard"><div className="upz-wrap"><div className="portal-section-heading"><div><span>Workspace</span><h2>Active projects</h2></div><div className="portal-heading-actions"><Link href={`/portal/${company.slug}/projects`}>View All Updates</Link><Link href={`/portal/${company.slug}/request/general`} className="primary">Start New Request</Link></div></div>{activeEngagements.length?<div className="portal-request-grid">{activeEngagements.map(project=><Link href={`/portal/${company.slug}/projects#engagement-${project.id}`} key={project.id}><span>{project.type}</span><h3>{project.name}</h3>{project.currentStatus&&<em className="portal-current-status">{project.currentStatus}</em>}{(project.activeWorkOrders>0||project.progress>0)&&<div>{project.activeWorkOrders>0&&<strong>{project.activeWorkOrders} active</strong>}{project.progress>0&&<em>{project.progress}% complete</em>}</div>}</Link>)}</div>:<div className="portal-empty-service"><h3>No active projects</h3><p>Choose an approved service below to start a request.</p><Link className="portal-empty-action" href={`/portal/${company.slug}/request/general`}>Start New Request</Link></div>}</div></section>
 <section id="services" className="portal-section portal-premium-services"><div className="upz-wrap"><div className="portal-section-heading portal-dark-heading"><div><span>Creative Capabilities</span><h2>Available services</h2><p>Select a service to start a focused request.</p></div></div>{services.length?<div className="portal-premium-service-grid">{services.map(service=><ServiceCard key={service.slug} service={service} company={company}/>)}</div>:<div className="portal-empty-service portal-empty-dark"><h3>{loading?"Loading services...":"No services enabled"}</h3><p>Contact UPZ to add services to this workspace.</p></div>}</div></section>
 <section className="portal-section portal-featured-packages"><div className="upz-wrap"><div className="portal-section-heading"><div><span>Curated Solutions</span><h2>Project packages</h2><p>Pre-built combinations of services and deliverables for common project needs.</p></div><Link className="portal-section-button" href={`/portal/${company.slug}/packages`}>View All Packages</Link></div><div className="portal-featured-package-grid">{featuredPackages.length?featuredPackages.map(pkg=><Link key={pkg.id} href={`/portal/${company.slug}/packages`}><span>Featured package</span><h3>{pkg.title}</h3><p>{pkg.description||"A curated combination of services, products, and deliverables."}</p><strong>Explore package →</strong></Link>):<Link href={`/portal/${company.slug}/packages`}><span>Curated solutions</span><h3>Browse Packages</h3><p>Start a complete project with a pre-built combination of services and products.</p><strong>View packages →</strong></Link>}</div></div></section>
 {merchandiseItems.length>0&&<section id="merchandise" className="portal-section portal-merch-section portal-merch-compact"><div className="upz-wrap"><div className="portal-section-heading"><div><span>Products</span><h2>Company merchandise</h2><p>Browse all approved merchandise in one compact catalog.</p></div></div><div className="portal-collection-nav portal-collection-filter"><button className={merchFilter==="all"?"active":""} onClick={()=>setMerchFilter("all")}>All</button>{groupedMerchandise.map(collection=><button className={merchFilter===collection.slug?"active":""} key={collection.slug} onClick={()=>setMerchFilter(collection.slug)}>{collection.name}<span>{collection.items.length}</span></button>)}</div><div className="portal-product-grid portal-merchandise-grid">{visibleMerchandise.map(item=><CatalogCard key={item.id} item={item} company={company} addItem={addItem}/>)}</div></div></section>}
 <section id="brand-assets" className="portal-section portal-brand-assets"><div className="upz-wrap"><div className="portal-section-heading"><div><span>Brand Assets</span><h2>Approved identity resources</h2></div>{digitalItems.length>0&&<strong>{digitalItems.length} downloadable item{digitalItems.length===1?"":"s"}</strong>}</div><div className="portal-brand-assets-grid"><div className="portal-brand-identity"><img src={company.logo||"/upz-logo.svg"} alt={`${company.name} logo`}/></div><div className="portal-brand-details"><article className="portal-brand-detail"><span>Primary Brand Color</span><div className="portal-color-swatch" style={{background:company.primaryColor}}/><strong>{company.primaryColor}</strong></article><article className="portal-brand-detail"><span>Secondary Brand Color</span><div className="portal-color-swatch" style={{background:company.secondaryColor}}/><strong>{company.secondaryColor}</strong></article><article className="portal-brand-detail"><span>Approved Logo</span><strong>{company.shortName} Identity</strong></article><article className="portal-brand-detail"><span>Support</span><strong>Request Another Format</strong></article></div></div>{digitalItems.length>0&&<div className="portal-product-grid" style={{marginTop:24}}>{digitalItems.map(item=><CatalogCard key={item.id} item={item} company={company} addItem={addItem}/>)}</div>}</div></section>
 </main>;
}
