"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";

type Task={id:number;title:string;status:string;assignedTo?:string|null;dueDate?:string|null};
type WorkOrder={id:number;title:string;description?:string|null;status:string;priority:string;budget?:number|null;internalCost?:number|null;assignedTo?:string|null;dueDate?:string|null;tasks:Task[];notes:Array<{id:number;body:string;author?:string|null;createdAt:string}>};
type Engagement={id:number;name:string;type:string;status:string;address?:string|null;city?:string|null;state?:string|null;postalCode?:string|null;description?:string|null;progress:number;totalBudget:number;totalCost:number;company:{name:string;shortName:string;slug?:string;logo?:string|null;primaryColor:string};assets:Array<{id:number;title:string;category:string;fileUrl?:string|null;description?:string|null}>;workOrders:WorkOrder[];activity:Array<{id:number;message:string;actor?:string|null;createdAt:string;workOrderTitle:string}>};
function money(value:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value||0)}
function progress(order:WorkOrder){return order.tasks.length?Math.round(order.tasks.filter((task)=>task.status==="complete").length/order.tasks.length*100):0}

export default function AdminEngagementDetailPage(){
 const params=useParams();const id=Array.isArray(params?.id)?params.id[0]:params?.id;const [data,setData]=useState<Engagement|null>(null);const [loading,setLoading]=useState(true);const [activeOrder,setActiveOrder]=useState<number|null>(null);const [tab,setTab]=useState("overview");
 useEffect(()=>{if(!id)return;fetch(`/api/admin/engagements/${id}`,{cache:"no-store"}).then((r)=>{if(!r.ok)throw new Error();return r.json()}).then((item)=>{setData(item);setActiveOrder(item.workOrders?.[0]?.id||null)}).finally(()=>setLoading(false));},[id]);
 const selected=useMemo(()=>data?.workOrders.find((item)=>item.id===activeOrder)||null,[data,activeOrder]);
 if(loading)return <main className="admin-engagement-page"><section className="admin-engagement-shell"><p>Loading project...</p></section></main>;
 if(!data)return <main className="admin-engagement-page"><section className="admin-engagement-shell"><h1>Project not found</h1><Link href="/admin/engagements">Back to engagements</Link></section></main>;
 const companySlug=data.company.slug||data.company.shortName.toLowerCase();
 return <main className="admin-engagement-page"><section className="admin-engagement-shell"><header className="admin-workspace-header"><div><span>{data.company.shortName} · {data.type}</span><h1>{data.name}</h1><p>{[data.address,data.city,data.state,data.postalCode].filter(Boolean).join(", ")||data.description||"Creative operations project"}</p></div><div className="admin-header-actions"><Link href="/admin/engagements">← All engagements</Link><Link href="/admin/operations">Open operations</Link><Link href={`/portal/${companySlug}/request/general?engagementId=${data.id}&engagementName=${encodeURIComponent(data.name)}`}>Add service</Link></div></header>
 <section className="admin-workspace-summary"><article><span>Status</span><strong>{data.status}</strong></article><article><span>Progress</span><strong>{data.progress}%</strong></article><article><span>Work orders</span><strong>{data.workOrders.length}</strong></article><article><span>Shared assets</span><strong>{data.assets.length}</strong></article></section>
 <nav className="admin-workspace-tabs">{["overview","work orders","assets","activity"].map((item)=><button key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>
 {tab==="overview"&&<div className="admin-workspace-layout"><section className="admin-workspace-main"><div className="admin-workspace-summary"><article><span>Total budget</span><strong>{money(data.totalBudget)}</strong></article><article><span>Internal cost</span><strong>{money(data.totalCost)}</strong></article><article><span>Projected margin</span><strong>{money(data.totalBudget-data.totalCost)}</strong></article><article><span>Shared assets</span><strong>{data.assets.length}</strong></article></div><section className="admin-workspace-orders"><div className="admin-workspace-section-head"><div><span>Production</span><h2>Work orders</h2></div><Link href={`/portal/${companySlug}/request/general?engagementId=${data.id}&engagementName=${encodeURIComponent(data.name)}`}>Add service</Link></div>{data.workOrders.map((order)=><button key={order.id} className={activeOrder===order.id?"active":""} onClick={()=>setActiveOrder(order.id)}><div><span>{order.priority} priority</span><h3>{order.title}</h3><p>{order.description||"Production workflow"}</p></div><div><strong>{progress(order)}%</strong><small>{order.status.replaceAll("_"," ")}</small></div></button>)}</section></section><aside className="admin-workspace-rail"><div className="admin-workspace-section-head"><div><span>Selected work order</span><h2>{selected?.title||"None"}</h2></div></div>{selected&&<><div className="admin-workspace-rail-meta"><span>Status<strong>{selected.status.replaceAll("_"," ")}</strong></span><span>Assigned<strong>{selected.assignedTo||"Unassigned"}</strong></span><span>Due<strong>{selected.dueDate?new Date(selected.dueDate).toLocaleDateString():"TBD"}</strong></span><span>Budget<strong>{money(Number(selected.budget||0))}</strong></span></div><div className="admin-workspace-task-list">{selected.tasks.map((task,index)=><article key={task.id} className={task.status}><span>{task.status==="complete"?"✓":index+1}</span><div><strong>{task.title}</strong><small>{task.assignedTo||"Unassigned"}{task.dueDate?` · ${new Date(task.dueDate).toLocaleDateString()}`:""}</small></div></article>)}</div><Link className="admin-primary-button" href="/admin/operations">Manage assignment and tasks</Link></>}</aside></div>}
 {tab==="work orders"&&<section className="admin-workspace-panel"><div className="admin-workspace-section-head"><div><span>All services</span><h2>Work order portfolio</h2></div><Link href="/admin/operations">Manage in operations</Link></div><div className="admin-workspace-order-grid">{data.workOrders.map((order)=><article key={order.id}><span>{order.status}</span><h3>{order.title}</h3><p>{order.description||"No description added."}</p><div><strong>{progress(order)}%</strong><small>{order.tasks.length} tasks</small></div></article>)}</div></section>}
 {tab==="assets"&&<section className="admin-workspace-panel"><div className="admin-workspace-section-head"><div><span>Shared resources</span><h2>Engagement assets</h2></div></div><div className="admin-workspace-asset-grid">{data.assets.map((asset)=><article key={asset.id}><span>{asset.category}</span><h3>{asset.title}</h3><p>{asset.description||"Available to every work order in this project."}</p>{asset.fileUrl&&<a href={asset.fileUrl} target="_blank">Open asset →</a>}</article>)}{data.assets.length===0&&<p>No shared assets uploaded yet.</p>}</div></section>}
 {tab==="activity"&&<section className="admin-workspace-panel"><div className="admin-workspace-section-head"><div><span>Timeline</span><h2>Recent activity</h2></div></div><div className="admin-workspace-activity">{data.activity.map((item)=><article key={`${item.id}-${item.workOrderTitle}`}><span>{new Date(item.createdAt).toLocaleString()}</span><div><strong>{item.workOrderTitle}</strong><p>{item.message}</p><small>{item.actor||"UPZ Admin"}</small></div></article>)}</div></section>}</section></main>;
}
