"use client";
import {useEffect,useMemo,useState} from "react";import Link from "next/link";
const COLUMNS=[['new','New'],['in_progress','In Progress'],['waiting_client','Waiting Client'],['review','Review'],['complete','Complete']] as const;
type Project={id:number;title:string;description?:string|null;status:string;priority:string;assignedTo?:string|null;dueDate?:string|null;budget?:number|null;internalCost?:number|null;company:{name:string;shortName:string;slug:string};engagement?:{id:number;name:string}|null;tasks:Array<{status:string}>;notes:Array<{body:string;createdAt:string}>};
type Data={projects:Project[];engagements:any[];assets:any[];services:any[];team:Array<{name:string;active:number;overdue:number;tasks:number}>};
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v||0);
export default function OperationsPage(){const[data,setData]=useState<Data|null>(null);const[query,setQuery]=useState('');const[assignee,setAssignee]=useState('all');const[tab,setTab]=useState('board');const[selected,setSelected]=useState<Project|null>(null);const[comment,setComment]=useState('');const load=()=>fetch('/api/admin/operations',{cache:'no-store'}).then(r=>r.json()).then(setData);useEffect(()=>{load()},[]);
 const projects=useMemo(()=>{if(!data)return[];return data.projects.filter(p=>(assignee==='all'||p.assignedTo===assignee)&&`${p.title} ${p.company.name} ${p.engagement?.name||''}`.toLowerCase().includes(query.toLowerCase()))},[data,query,assignee]);
 async function move(id:number,status:string){await fetch(`/api/admin/work-orders/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await load()}
 async function approve(decision:string){if(!selected)return;await fetch(`/api/admin/work-orders/${selected.id}/approval`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,comment})});setComment('');setSelected(null);await load()}
 if(!data)return <main className="ops-page"><p>Loading operations...</p></main>;
 const active=projects.filter(p=>!['complete','completed','cancelled'].includes(p.status)).length;const overdue=projects.filter(p=>p.dueDate&&new Date(p.dueDate)<new Date()&&!['complete','completed'].includes(p.status)).length;const revenue=projects.reduce((s,p)=>s+Number(p.budget||0),0);const cost=projects.reduce((s,p)=>s+Number(p.internalCost||0),0);
 return <main className="ops-page"><header className="ops-head"><div><span>UPZ WORKSPACE</span><h1>Operations</h1><p>Production, team workload, assets, approvals, and engagement delivery in one place.</p></div><Link href="/admin/engagements">View engagements →</Link></header>
 <section className="ops-kpis"><article><span>Active work orders</span><strong>{active}</strong></article><article><span>Needs attention</span><strong>{overdue}</strong></article><article><span>Tracked revenue</span><strong>{money(revenue)}</strong></article><article><span>Projected margin</span><strong>{money(revenue-cost)}</strong></article><article><span>Shared assets</span><strong>{data.assets.length}</strong></article></section>
 <nav className="ops-tabs">{[['board','Production Board'],['team','Team'],['assets','Assets'],['approvals','Approvals']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
 <div className="ops-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search work orders, companies, engagements..."/><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="all">All team members</option>{data.team.map(t=><option key={t.name}>{t.name}</option>)}</select></div>
 {tab==='board'&&<section className="ops-board">{COLUMNS.map(([status,label])=><article className="ops-column" key={status}><header><strong>{label}</strong><span>{projects.filter(p=>p.status===status).length}</span></header><div>{projects.filter(p=>p.status===status).map(p=><button className="ops-card" key={p.id} onClick={()=>setSelected(p)}><small>{p.company.shortName} · {p.priority}</small><h3>{p.title}</h3><p>{p.engagement?.name||'General engagement'}</p><div><span>{p.assignedTo||'Unassigned'}</span><span>{p.dueDate?new Date(p.dueDate).toLocaleDateString():'No due date'}</span></div><select value={p.status} onClick={e=>e.stopPropagation()} onChange={e=>move(p.id,e.target.value)}>{COLUMNS.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></button>)}</div></article>)}</section>}
 {tab==='team'&&<section className="ops-grid">{data.team.length?data.team.map(t=><article className="ops-panel" key={t.name}><div className="ops-avatar">{t.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><h3>{t.name}</h3><p>Creative operations team member</p><dl><div><dt>Active assignments</dt><dd>{t.active}</dd></div><div><dt>Tracked tasks</dt><dd>{t.tasks}</dd></div><div><dt>Overdue</dt><dd>{t.overdue}</dd></div></dl><div className="ops-capacity"><i style={{width:`${Math.min(100,t.active*18)}%`}}/></div></article>):<div className="ops-empty">Assign team members to work orders to build the workload directory.</div>}</section>}
 {tab==='assets'&&<section className="ops-assets">{data.assets.map(a=><article key={a.id}><div className="ops-asset-preview">{a.fileUrl&&/\.(jpg|jpeg|png|webp|gif)$/i.test(a.fileUrl)?<img src={a.fileUrl} alt=""/>:<span>{a.category?.slice(0,2).toUpperCase()||'AS'}</span>}</div><small>{a.engagement.company.shortName} · {a.category}</small><h3>{a.title}</h3><p>{a.engagement.name}</p>{a.fileUrl&&<a href={a.fileUrl} target="_blank">Open asset →</a>}</article>)}{!data.assets.length&&<div className="ops-empty">No engagement assets have been uploaded yet.</div>}</section>}
 {tab==='approvals'&&<section className="ops-approval-list">{projects.filter(p=>['waiting_client','review'].includes(p.status)).map(p=><article key={p.id}><div><small>{p.company.shortName} · {p.status.replaceAll('_',' ')}</small><h3>{p.title}</h3><p>{p.engagement?.name||'General engagement'}</p></div><button onClick={()=>setSelected(p)}>Open review</button></article>)}{!projects.some(p=>['waiting_client','review'].includes(p.status))&&<div className="ops-empty">No work orders are currently waiting for approval.</div>}</section>}
 {selected&&<div className="ops-drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="ops-drawer" onMouseDown={e=>e.stopPropagation()}><button className="ops-close" onClick={()=>setSelected(null)}>×</button><small>{selected.company.name}</small><h2>{selected.title}</h2><p>{selected.description||selected.engagement?.name||'Production work order'}</p><div className="ops-drawer-meta"><span>Status<strong>{selected.status.replaceAll('_',' ')}</strong></span><span>Assigned<strong>{selected.assignedTo||'Unassigned'}</strong></span><span>Tasks<strong>{selected.tasks.length}</strong></span><span>Budget<strong>{money(Number(selected.budget||0))}</strong></span></div><label>Approval note<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add client feedback or an internal approval note..."/></label><div className="ops-actions"><button onClick={()=>approve('approved')}>Approve</button><button onClick={()=>approve('changes_requested')}>Request changes</button><button onClick={()=>approve('sent_for_review')}>Send for review</button></div>{selected.engagement&&<Link href={`/admin/engagements/${selected.engagement.id}`}>Open full engagement →</Link>}</aside></div>}
 </main>}
