"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { AdminButton, AdminCard, AdminEmptyState, AdminGrid, AdminHeader, AdminPage, AdminSection, AdminSectionHeader, AdminStats, AdminTabs, AdminToolbar, StatCard } from "@/components/admin/AdminUI";

type Project={id:number;name:string;type:string;status:string;address?:string|null;city?:string|null;state?:string|null;progress:number;totalBudget:number;cost:number;activeOrders:number;assetCount:number;company:{name:string;shortName:string;logo?:string|null;primaryColor:string};workOrders:Array<{id:number;title:string;status:string;priority:string;dueDate?:string|null}>};
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value||0);
const isSoon=(date?:string|null)=>{if(!date)return false;const days=(new Date(date).getTime()-Date.now())/86400000;return days>=0&&days<=7};
const completeStatus=(value:string)=>["complete","completed","closed"].includes(value.toLowerCase());

export default function AdminProjectsPage(){
 const[items,setItems]=useState<Project[]>([]);const[loading,setLoading]=useState(true);const[query,setQuery]=useState("");const[status,setStatus]=useState("active");
 useEffect(()=>{const requested=new URLSearchParams(window.location.search).get("status");if(requested&&["all","active","complete","archived"].includes(requested))setStatus(requested);fetch("/api/admin/engagements",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>setItems(Array.isArray(data)?data:[])).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>items.filter(item=>{const itemComplete=completeStatus(item.status)||Boolean(item.workOrders.length)&&item.workOrders.every(order=>completeStatus(order.status));const matchesStatus=status==="all"||(status==="active"?!itemComplete&&item.status!=="archived":status==="complete"?itemComplete:item.status===status);const haystack=`${item.name} ${item.company.name} ${item.address||""}`.toLowerCase();return matchesStatus&&haystack.includes(query.toLowerCase())}),[items,query,status]);
 const completed=items.filter(item=>completeStatus(item.status)||Boolean(item.workOrders.length)&&item.workOrders.every(order=>completeStatus(order.status))).length;
 const active=items.filter(item=>item.status!=="archived"&&!(completeStatus(item.status)||Boolean(item.workOrders.length)&&item.workOrders.every(order=>completeStatus(order.status)))).length;
 const budget=items.reduce((sum,item)=>sum+item.totalBudget,0),margin=items.reduce((sum,item)=>sum+item.totalBudget-item.cost,0),workOrders=items.reduce((sum,item)=>sum+item.workOrders.length,0);
 const attention=items.flatMap(item=>item.workOrders.filter(order=>!completeStatus(order.status)&&(order.priority==="urgent"||isSoon(order.dueDate))).map(order=>({...order,projectId:item.id,projectName:item.name}))).slice(0,5);
 return <AdminPage className="admin-engagement-page">
  <AdminHeader eyebrow="UPZ Workspace" title="Projects" description="Manage every property or campaign, its work orders, shared assets, deadlines, and completed history from one project directory." actions={<><AdminButton variant="outline" href="/admin/projects?status=complete">Completed Projects</AdminButton><AdminButton href="/admin/operations">Open Work Management</AdminButton></>}/>
  <AdminStats><StatCard label="Total projects" value={items.length}/><StatCard label="Active projects" value={active}/><StatCard label="Completed projects" value={completed}/><StatCard label="Work orders" value={workOrders}/><StatCard label="Tracked budget" value={money(budget)}/></AdminStats>
  {attention.length>0&&status!=="complete"&&<AdminSection><AdminSectionHeader eyebrow="Needs attention" title="Upcoming and urgent work"/><div className="admin-engagement-orders">{attention.map(order=><Link key={`${order.projectId}-${order.id}`} href={`/admin/projects/${order.projectId}`}><span>{order.projectName} · {order.title}<b>{order.dueDate?new Date(order.dueDate).toLocaleDateString():order.priority}</b></span></Link>)}</div></AdminSection>}
  <AdminTabs>{[["active","Active"],["complete","Completed"],["archived","Archived"],["all","All Projects"]].map(([value,label])=><button type="button" key={value} className={status===value?"active":""} onClick={()=>setStatus(value)}>{label}</button>)}</AdminTabs>
  <AdminToolbar><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search project, property, campaign, or company"/><span>{filtered.length} project{filtered.length===1?"":"s"}</span></AdminToolbar>
  <AdminSection><AdminSectionHeader eyebrow={status==="complete"?"Project History":"Projects"} title={status==="complete"?"Completed projects":"Project directory"}/>{loading?<p>Loading projects...</p>:filtered.length===0?<AdminEmptyState>{status==="complete"?"No completed projects yet.":"No projects match this view."}</AdminEmptyState>:<AdminGrid columns={2} className="admin-engagement-grid">{filtered.map(item=><AdminCard key={item.id} className="admin-engagement-card"><Link href={`/admin/projects/${item.id}`} className="admin-engagement-card-link"><div className="admin-engagement-card-top"><div><span className="admin-ui-eyebrow">{item.company.shortName} · {item.type}</span><h2>{item.name}</h2><p>{[item.address,item.city,item.state].filter(Boolean).join(", ")||"Campaign project"}</p></div><em>{completeStatus(item.status)?"complete":item.status}</em></div><div className="admin-engagement-progress"><div><strong>Overall progress</strong><span>{item.progress}%</span></div><i><b style={{width:`${item.progress}%`}}/></i></div><div className="admin-engagement-card-metrics"><div><small>Active orders</small><strong>{item.activeOrders}</strong></div><div><small>Assets</small><strong>{item.assetCount}</strong></div><div><small>Budget</small><strong>{money(item.totalBudget)}</strong></div><div><small>Margin</small><strong>{money(item.totalBudget-item.cost)}</strong></div></div><div className="admin-engagement-orders">{item.workOrders.slice(0,4).map(order=><span key={order.id}>{order.title}<b>{order.status.replaceAll("_"," ")}</b></span>)}{item.workOrders.length===0&&<span>No work orders yet</span>}</div><footer>Open project <b>→</b></footer></Link></AdminCard>)}</AdminGrid>}</AdminSection>
 </AdminPage>
}
