"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../timeline/page.module.css";
import { isProjectComplete, normalizeProjectStage, projectStageLabel } from "@/lib/project-status";

type Task={id:number;title:string;status:string;dueDate?:string|null};
type Project={id:number;title:string;status:string;priority:string;startDate?:string|null;dueDate?:string|null;assignedTo?:string|null;company:{shortName:string;name:string;slug:string};engagement?:{id:number;name:string}|null;tasks:Task[]};
type Data={projects:Project[]};
const DAY=86400000;
const taskComplete=new Set(["complete","completed"]);
function startOfDay(value:Date){const date=new Date(value);date.setHours(0,0,0,0);return date}
function addDays(value:Date,days:number){return new Date(value.getTime()+days*DAY)}
function clamp(value:number,min:number,max:number){return Math.min(max,Math.max(min,value))}
function dateLabel(value:Date){return value.toLocaleDateString("en-US",{month:"short",day:"numeric"})}

export default function ProjectsPage(){
 const [data,setData]=useState<Data|null>(null);const [query,setQuery]=useState("");const [showCompleted,setShowCompleted]=useState(false);const [view,setView]=useState<"portfolio"|"timeline">("portfolio");const [rangeStart,setRangeStart]=useState(()=>addDays(startOfDay(new Date()),-7));const rangeDays=42;const rangeEnd=addDays(rangeStart,rangeDays-1);
 useEffect(()=>{fetch("/api/admin/operations",{cache:"no-store"}).then(r=>r.json()).then((value:Data)=>setData({...value,projects:value.projects.map(project=>({...project,status:normalizeProjectStage(project.status)}))}))},[]);
 const days=useMemo(()=>Array.from({length:rangeDays},(_,index)=>addDays(rangeStart,index)),[rangeStart]);
 const projects=useMemo(()=>!data?[]:data.projects.filter(project=>showCompleted||!isProjectComplete(project.status)).filter(project=>`${project.title} ${project.company.name} ${project.engagement?.name||""} ${project.assignedTo||""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>new Date(a.dueDate||"2999-12-31").getTime()-new Date(b.dueDate||"2999-12-31").getTime()),[data,query,showCompleted]);
 if(!data)return <main className={styles.page}><p>Loading projects...</p></main>;
 const todayOffset=clamp(((startOfDay(new Date()).getTime()-rangeStart.getTime())/DAY)/rangeDays*100,0,100);
 return <main className={styles.page}>
  <header className={styles.header}><div><span>PROJECT MANAGEMENT</span><h1>Projects</h1><p>The master view for every approved project. Portfolio, Production Board, and Timeline all use the same live stage, schedule, assignment, and task data.</p></div><Link href="/admin/operations">Open Production Board →</Link></header>
  <section className={styles.summary}><article><span>Active projects</span><strong>{data.projects.filter(p=>!isProjectComplete(p.status)).length}</strong></article><article><span>New + planning</span><strong>{data.projects.filter(p=>["new","planning"].includes(normalizeProjectStage(p.status))).length}</strong></article><article><span>Waiting client</span><strong>{data.projects.filter(p=>normalizeProjectStage(p.status)==="waiting_client").length}</strong></article><article><span>Unscheduled</span><strong>{data.projects.filter(p=>!p.startDate&&!p.dueDate).length}</strong></article></section>
  <section className={styles.controls}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects, clients, campaigns, or assignees..."/><button onClick={()=>setView("portfolio")} className={view==="portfolio"?"active":""}>Portfolio</button><button onClick={()=>setView("timeline")} className={view==="timeline"?"active":""}>Timeline</button><label><input type="checkbox" checked={showCompleted} onChange={e=>setShowCompleted(e.target.checked)}/> Show completed</label></section>
  {view==="portfolio"&&<section className="project-master-grid">{projects.map(project=>{const complete=project.tasks.filter(task=>taskComplete.has(task.status.toLowerCase())).length;const progress=project.tasks.length?Math.round(complete/project.tasks.length*100):0;return <article className="project-master-card" key={project.id}><div><small>{project.company.shortName} · {project.priority}</small><strong>{projectStageLabel(project.status)}</strong></div><h2>{project.title}</h2><p>{project.engagement?.name||"General project"}</p><dl><div><dt>Assigned</dt><dd>{project.assignedTo||"Unassigned"}</dd></div><div><dt>Due</dt><dd>{project.dueDate?new Date(project.dueDate).toLocaleDateString():"Unscheduled"}</dd></div></dl><i><b style={{width:`${progress}%`}}/></i><footer><span>{progress}% complete</span><Link href={`/admin/operations?project=${project.id}`}>Manage in Operations →</Link></footer></article>})}{!projects.length&&<div className={styles.empty}>No projects match this view.</div>}</section>}
  {view==="timeline"&&<><section className={styles.controls}><button onClick={()=>setRangeStart(addDays(rangeStart,-14))}>← Earlier</button><button onClick={()=>setRangeStart(addDays(startOfDay(new Date()),-7))}>Today</button><button onClick={()=>setRangeStart(addDays(rangeStart,14))}>Later →</button><span>{dateLabel(rangeStart)} – {dateLabel(rangeEnd)}</span></section><section className={styles.timeline}><div className={styles.timelineHead}><div className={styles.projectHeading}>Project</div><div className={styles.days}>{days.map(day=><div className={day.getDay()===0||day.getDay()===6?styles.weekend:""} key={day.toISOString()}><strong>{day.toLocaleDateString("en-US",{weekday:"short"}).slice(0,1)}</strong><span>{day.getDate()}</span></div>)}</div></div><div className={styles.timelineBody}><i className={styles.today} style={{left:`calc(320px + (100% - 320px) * ${todayOffset/100})`}}/>{projects.map(project=>{const start=startOfDay(new Date(project.startDate||project.dueDate||new Date()));const due=startOfDay(new Date(project.dueDate||project.startDate||new Date()));const left=clamp((start.getTime()-rangeStart.getTime())/DAY,0,rangeDays);const right=clamp((due.getTime()-rangeStart.getTime())/DAY+1,0,rangeDays);const complete=project.tasks.filter(task=>taskComplete.has(task.status.toLowerCase())).length;const progress=project.tasks.length?Math.round(complete/project.tasks.length*100):0;const stage=normalizeProjectStage(project.status);return <article className={styles.row} key={project.id}><div className={styles.projectInfo}><small>{project.company.shortName} · {projectStageLabel(stage)}</small><h3><Link href={`/admin/operations?project=${project.id}`}>{project.title}</Link></h3><p>{project.engagement?.name||"General project"} · {project.assignedTo||"Unassigned"}</p></div><div className={styles.track}><div className={`${styles.bar} ${styles[`status_${stage}`]||""}`} style={{left:`${left/rangeDays*100}%`,width:`${Math.max((right-left)/rangeDays*100,2.4)}%`}} title={`${dateLabel(start)} – ${dateLabel(due)}`}><i style={{width:`${progress}%`}}/><span>{progress}%</span></div>{project.tasks.filter(task=>task.dueDate).map(task=>{const offset=clamp((startOfDay(new Date(task.dueDate!)).getTime()-rangeStart.getTime())/DAY,0,rangeDays);return <b className={styles.milestone} style={{left:`${offset/rangeDays*100}%`}} title={`${task.title}: ${dateLabel(new Date(task.dueDate!))}`} key={task.id}/>})}</div></article>})}{!projects.length&&<div className={styles.empty}>No projects match this timeline view.</div>}</div></section></>}
 </main>
}
