import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "./portal-responsive.css";
import "./portal-requests.css";
import "./admin.css";
import "./admin-forms.css";
import "./admin-requests.css";
import "./packages.css";
import "./projects.css";
import "./ui-polish.css";
import "./client-portal-polish.css";
import "./final-polish.css";
import "./workflow-polish.css";
import "./service-list-fix.css";
import "./client-projects.css";
import "./command-palette.css";
import "./service-library.css";
import "./admin-workspace.css";
import "./admin-contrast.css";
import "./company-workspace.css";
import "./portal-admin-polish.css";
import "./workflow-engine.css";
import "./engagement-workspaces.css";
import "./admin-engagement-prototype.css";
import "./operations-core.css";
import "./admin-consistency.css";
import "./admin-ui-v1.css";
import "./project-workflow.css";
import "./workflow-final.css";
import "./review-round.css";
import "./project-conversation-polish.css";
import "./review-flow-polish.css";
import "./stage-conversations.css";
import "./deliverables.css";
import "./portal-workspace-nav.css";
import "./workflow-unification.css";
import "./workspace-unification.css";
import "./project-os.css";
import "./task-engine.css";
import "./my-tasks.css";
import "./staff-auth.css";
import "./team-management.css";
import "./workspace-stabilization.css";
import "./admin-design-system.css";
import "./admin-system-refinements.css";
import Providers from "./providers";
import Cart from "@/components/Cart";
import SiteChrome from "@/components/SiteChrome";
import AdminCommandPalette from "@/components/AdminCommandPalette";

const montserrat=Montserrat({subsets:["latin"],weight:["400","500","600","700","800","900"],display:"swap"});
export const metadata:Metadata={title:"UPZ Store | Branded Merchandise & CRE Packages",description:"Branded merchandise, promotional products, and curated CRE packages by UPZ Design."};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="en"><body className={montserrat.className}><Providers><SiteChrome>{children}</SiteChrome><AdminCommandPalette/><Cart/></Providers></body></html>;}