export type PricingRule={id:string;label:string;sourceKey:string;matchType:"selected"|"equals"|"number_min";matchValue?:string;clientAmount:number;internalCost:number;active:boolean};
export type PricingConfig={basePrice:number;baseCost:number;rules:PricingRule[]};
export type EstimateLine={id:string;label:string;source:string;clientAmount:number;internalCost:number};
export type EstimateResult={service:string;basePrice:number;baseCost:number;clientPrice:number;internalCost:number;margin:number;marginPercent:number;lines:EstimateLine[];answers:Record<string,unknown>;propertyContext:Record<string,unknown>};

export function normalizePricing(value:unknown):PricingConfig{const source=value&&typeof value==="object"?value as Record<string,unknown>:{};return{basePrice:Number(source.basePrice)||0,baseCost:Number(source.baseCost)||0,rules:Array.isArray(source.rules)?source.rules.map((rule:any,index:number)=>({id:String(rule?.id||`rule-${index}`),label:String(rule?.label||"Pricing rule"),sourceKey:String(rule?.sourceKey||""),matchType:["selected","equals","number_min"].includes(rule?.matchType)?rule.matchType:"selected",matchValue:rule?.matchValue==null?"":String(rule.matchValue),clientAmount:Number(rule?.clientAmount)||0,internalCost:Number(rule?.internalCost)||0,active:rule?.active!==false})):[]};}

export function parseRequestPayload(value?:string|null){const source=value||"",marker="__UPZ_CONTEXT__",index=source.lastIndexOf(marker),details=index>=0?source.slice(0,index).trim():source.trim();let context:Record<string,any>={};if(index>=0)try{context=JSON.parse(source.slice(index+marker.length).trim())}catch{}const answers:Record<string,unknown>={...(context.answers&&typeof context.answers==="object"?context.answers:{})};if(!Object.keys(answers).length){for(const block of details.split(/\n\s*\n/)){const split=block.indexOf(":");if(split<1)continue;const key=block.slice(0,split).trim().toLowerCase().replace(/[^a-z0-9]+(.)/g,(_,c)=>String(c||"").toUpperCase());const raw=block.slice(split+1).trim();answers[key]=raw.includes(", ")?raw.split(", ").map(item=>item.trim()):raw;}}return{details,context,answers};}

function text(value:unknown){return Array.isArray(value)?value.join(" ").toLowerCase():String(value??"").toLowerCase();}
function ruleMatches(rule:PricingRule,answers:Record<string,unknown>,property:Record<string,unknown>){const source=answers[rule.sourceKey]??property[rule.sourceKey];if(rule.matchType==="selected")return Array.isArray(source)?source.some(item=>text(item)===text(rule.matchValue)||text(item).includes(text(rule.matchValue))):source===true||text(source).includes(text(rule.matchValue||"true"));if(rule.matchType==="equals")return text(source)===text(rule.matchValue);if(rule.matchType==="number_min")return Number(String(source??"").replace(/[^0-9.-]/g,""))>=Number(rule.matchValue||0);return false;}

export function calculateEstimate(service:string,pricingValue:unknown,answers:Record<string,unknown>,propertyContext:Record<string,unknown>={}):EstimateResult{const pricing=normalizePricing(pricingValue),lines:EstimateLine[]=[{id:"base",label:`${service} base`,source:"Base service",clientAmount:pricing.basePrice,internalCost:pricing.baseCost}];for(const rule of pricing.rules.filter(item=>item.active&&ruleMatches(item,answers,propertyContext)))lines.push({id:rule.id,label:rule.label,source:rule.sourceKey,clientAmount:rule.clientAmount,internalCost:rule.internalCost});const clientPrice=lines.reduce((sum,item)=>sum+item.clientAmount,0),internalCost=lines.reduce((sum,item)=>sum+item.internalCost,0),margin=clientPrice-internalCost;return{service,basePrice:pricing.basePrice,baseCost:pricing.baseCost,clientPrice,internalCost,margin,marginPercent:clientPrice?Math.round(margin/clientPrice*100):0,lines,answers,propertyContext};}
