import { prisma } from "@/lib/prisma";
import { INTAKE_FORMS, type IntakeDefinition, type IntakeField } from "@/lib/intake-forms";

const imageCategory=(url?:string)=>(url?`image:${url}`:"creative");
const imageFromCategory=(category?:string|null)=>category?.startsWith("image:")?category.slice(6):undefined;
const hiddenClientField=(field:{key?:string;label?:string})=>["deadline","requestedDeadline","budget","budgetRange","budget_range"].includes(String(field.key))||/deadline|budget/i.test(String(field.label||""));

function decodeOptions(value:any){
 if(Array.isArray(value))return{options:value};
 if(value&&typeof value==="object")return{options:Array.isArray(value.choices)?value.choices:[],visibility:value.visibility||"both",checklistStage:value.checklistStage||undefined};
 return{options:[]};
}
function encodeOptions(field:IntakeField){return{choices:field.options||[],visibility:field.visibility||"both",checklistStage:field.checklistStage||null};}
function toDefinition(service:any):IntakeDefinition{return{slug:service.slug,name:service.name,description:service.description,imageUrl:imageFromCategory(service.category)||INTAKE_FORMS[service.slug]?.imageUrl,fields:(service.fields||[]).filter((field:any)=>!hiddenClientField(field)).map((field:any)=>{const config=decodeOptions(field.options);return{key:field.key,label:field.label,type:field.type,placeholder:field.placeholder||undefined,helpText:field.helpText||undefined,required:Boolean(field.required),wide:Boolean(field.wide),...config};})};}

export async function ensureServiceLibrary(){const count=await prisma.service.count();if(count>0)return;for(const[serviceIndex,service]of Object.values(INTAKE_FORMS).entries()){await prisma.service.create({data:{slug:service.slug,name:service.name,description:service.description,category:imageCategory(service.imageUrl),sortOrder:serviceIndex,fields:{create:service.fields.map((field,index)=>({key:field.key,label:field.label,type:field.type,placeholder:field.placeholder,helpText:field.helpText,required:Boolean(field.required),wide:Boolean(field.wide),options:encodeOptions(field),sortOrder:index}))}}});}}
export async function getServiceLibraryFromDb(){await ensureServiceLibrary();const services=await prisma.service.findMany({where:{active:true},orderBy:[{sortOrder:"asc"},{name:"asc"}],include:{fields:{orderBy:{sortOrder:"asc"}}}});return services.map(toDefinition);}
export async function replaceServiceLibrary(definitions:IntakeDefinition[]){await prisma.$transaction(async tx=>{for(let serviceIndex=0;serviceIndex<definitions.length;serviceIndex++){const definition=definitions[serviceIndex];const service=await tx.service.upsert({where:{slug:definition.slug},update:{name:definition.name,description:definition.description,category:imageCategory(definition.imageUrl),active:true,sortOrder:serviceIndex},create:{slug:definition.slug,name:definition.name,description:definition.description,category:imageCategory(definition.imageUrl),sortOrder:serviceIndex}});await tx.serviceField.deleteMany({where:{serviceId:service.id}});const fields=definition.fields.filter(field=>!hiddenClientField(field));if(fields.length)await tx.serviceField.createMany({data:fields.map((field,index)=>({serviceId:service.id,key:field.key,label:field.label,type:field.type,placeholder:field.placeholder||null,helpText:field.helpText||null,required:Boolean(field.required),wide:Boolean(field.wide),options:encodeOptions(field),sortOrder:index}))});}});return getServiceLibraryFromDb();}
export async function getCompanyServices(slug:string,enabledOnly=false){await ensureServiceLibrary();const company=await prisma.company.findUnique({where:{slug}});if(!company)return null;const assignments=await prisma.companyService.findMany({where:{companyId:company.id},include:{service:{include:{fields:{orderBy:{sortOrder:"asc"}}}}},orderBy:{sortOrder:"asc"}});if(assignments.length===0){const services=await prisma.service.findMany({where:{active:true},orderBy:{sortOrder:"asc"}});await prisma.companyService.createMany({data:services.map((service,index)=>({companyId:company.id,serviceId:service.id,enabled:true,sortOrder:index})),skipDuplicates:true});return getCompanyServices(slug,enabledOnly);}return assignments.filter(item=>!enabledOnly||item.enabled).map(item=>({...toDefinition(item.service),enabled:item.enabled,featured:item.featured,customPrice:item.customPrice,customTimeline:item.customTimeline}));}
export async function saveCompanyServices(slug:string,enabledSlugs:string[]){await ensureServiceLibrary();const company=await prisma.company.findUnique({where:{slug}});if(!company)return null;const services=await prisma.service.findMany({where:{active:true}});await prisma.$transaction(services.map((service,index)=>prisma.companyService.upsert({where:{companyId_serviceId:{companyId:company.id,serviceId:service.id}},update:{enabled:enabledSlugs.includes(service.slug),sortOrder:index},create:{companyId:company.id,serviceId:service.id,enabled:enabledSlugs.includes(service.slug),sortOrder:index}})));return getCompanyServices(slug,false);}