import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireStaffSession } from "@/lib/staff-auth";

export async function PATCH(request:NextRequest,context:{params:Promise<{id:string}>}){
 const session=await requireStaffSession();if(!session)return NextResponse.json({error:"Authentication required"},{status:401});
 const {id}=await context.params;const body=await request.json();const taskId=Number(id);const existing=await prisma.projectTask.findUnique({where:{id:taskId},include:{attachments:true,checklist:true}});if(!existing)return NextResponse.json({error:"Task not found"},{status:404});
 if(session.role==="contributor"&&existing.assignedTo!==session.name)return NextResponse.json({error:"You can only update tasks assigned to you"},{status:403});
 const completing=body.status!==undefined&&["complete","completed"].includes(String(body.status).toLowerCase())&&!["complete","completed"].includes(existing.status.toLowerCase());
 if(completing&&existing.description?.includes("__UPZ_REQUIRES_FILES__")&&existing.attachments.length===0)return NextResponse.json({error:"Upload at least one file before completing this delivery stage.",code:"FILES_REQUIRED"},{status:409});
 if(completing&&existing.checklist.some(item=>!item.completed))return NextResponse.json({error:"Complete every checklist item before closing this stage.",code:"CHECKLIST_INCOMPLETE"},{status:409});

 if(session.role==="admin"&&body.sortOrder!==undefined){const siblings=await prisma.projectTask.findMany({where:{projectId:existing.projectId},orderBy:{sortOrder:"asc"}});const withoutCurrent=siblings.filter(item=>item.id!==taskId);const target=Math.max(0,Math.min(withoutCurrent.length,Number(body.sortOrder)||0));withoutCurrent.splice(target,0,existing);await prisma.$transaction(withoutCurrent.map((item,index)=>prisma.projectTask.update({where:{id:item.id},data:{sortOrder:index}})));}
 const contributorData=session.role==="contributor"?{status:body.status===undefined?undefined:String(body.status)}:{title:body.title===undefined?undefined:String(body.title).trim(),description:body.description===undefined?undefined:body.description?String(body.description).trim():null,status:body.status===undefined?undefined:String(body.status),priority:body.priority===undefined?undefined:String(body.priority),assignedTo:body.assignedTo===undefined?undefined:body.assignedTo?String(body.assignedTo).trim():null,dueDate:body.dueDate===undefined?undefined:body.dueDate?new Date(body.dueDate):null};
 const task=await prisma.projectTask.update({where:{id:taskId},data:contributorData});let message=`Work stage updated: ${task.title}.`;if(body.status!==undefined&&existing.status!==task.status)message=task.status==="complete"?`Work stage completed: ${task.title}.`:`Work stage “${task.title}” moved to ${task.status.replaceAll("_"," ")}.`;else if(session.role==="admin"&&body.assignedTo!==undefined&&existing.assignedTo!==task.assignedTo)message=task.assignedTo?`Work stage “${task.title}” assigned to ${task.assignedTo}.`:`Work stage assignment removed: ${task.title}.`;else if(session.role==="admin"&&body.sortOrder!==undefined)message=`Work stage order updated: ${task.title}.`;await prisma.projectActivity.create({data:{projectId:task.projectId,type:"task_updated",message,actor:session.name}});
 let nextStage:null|{id:number;title:string;assignedTo:string|null}=null;let projectCompleted=false;
 if(["complete","completed"].includes(task.status.toLowerCase())&&!["complete","completed"].includes(existing.status.toLowerCase())){const next=await prisma.projectTask.findFirst({where:{projectId:task.projectId,sortOrder:{gt:task.sortOrder}},orderBy:{sortOrder:"asc"}});if(next&&["todo","blocked","pending"].includes(next.status.toLowerCase())){const activated=await prisma.projectTask.update({where:{id:next.id},data:{status:"ready"}});nextStage={id:activated.id,title:activated.title,assignedTo:activated.assignedTo};await prisma.projectActivity.create({data:{projectId:task.projectId,type:"stage_ready",message:`Next stage is ready: ${activated.title}${activated.assignedTo?` · assigned to ${activated.assignedTo}`:""}.`,actor:"Workflow Automation"}});}const remaining=await prisma.projectTask.count({where:{projectId:task.projectId,status:{notIn:["complete","completed"]}}});if(remaining===0){await prisma.project.update({where:{id:task.projectId},data:{status:"complete"}});projectCompleted=true;await prisma.projectActivity.create({data:{projectId:task.projectId,type:"project_completed",message:"All work stages are complete. The work order was marked complete.",actor:"Workflow Automation"}});}}
 return NextResponse.json({task,nextStage,projectCompleted,message:projectCompleted?"Work order completed.":nextStage?`Stage completed. ${nextStage.title} is now ready.`:"Stage updated."});
}

export async function DELETE(_request:NextRequest,context:{params:Promise<{id:string}>}){const session=await requireStaffSession(["admin"]);if(!session)return NextResponse.json({error:"Admin access required"},{status:403});const {id}=await context.params;const task=await prisma.projectTask.findUnique({where:{id:Number(id)}});if(!task)return NextResponse.json({error:"Task not found"},{status:404});await prisma.projectTask.delete({where:{id:task.id}});const remaining=await prisma.projectTask.findMany({where:{projectId:task.projectId},orderBy:{sortOrder:"asc"}});await prisma.$transaction(remaining.map((item,index)=>prisma.projectTask.update({where:{id:item.id},data:{sortOrder:index}})));await prisma.projectActivity.create({data:{projectId:task.projectId,type:"task_removed",message:`Work stage removed: ${task.title}.`,actor:session.name}});return NextResponse.json({ok:true});}
