import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getWorkflowTemplate, type WorkflowStep } from "@/lib/workflow-templates";

function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||`project-${Date.now()}`;}
function parseRequestDescription(value?:string|null){const source=value||"";const marker="__UPZ_CONTEXT__";const index=source.lastIndexOf(marker);if(index<0)return{description:source||null,context:null as any};const description=source.slice(0,index).trim()||null;try{return{description,context:JSON.parse(source.slice(index+marker.length).trim())};}catch{return{description:source||null,context:null as any};}}
type ApprovalStep=WorkflowStep&{assignedTo?:string|null;requiresFiles?:boolean};
function approvalStages(value:unknown,fallback:WorkflowStep[]):ApprovalStep[]{if(!Array.isArray(value))return fallback;const stages=value.map((stage:any,index)=>({title:String(stage?.title||"").trim(),description:String(stage?.description||"").trim(),durationDays:Number.isFinite(Number(stage?.durationDays))?Math.max(0,Number(stage.durationDays)):index,clientVisible:stage?.clientVisible!==false,assignedTo:stage?.assignedTo?String(stage.assignedTo).trim():null,requiresFiles:Boolean(stage?.requiresFiles)})).filter(stage=>stage.title);return stages.length?stages:fallback;}
function scaledOffset(step:ApprovalStep,index:number,workflow:ApprovalStep[],startDate:Date,dueDate:Date){const totalDays=Math.max(0,Math.round((dueDate.getTime()-startDate.getTime())/86400000));const maxTemplate=Math.max(1,...workflow.map((item,itemIndex)=>Number(item.durationDays??itemIndex)));const raw=Number(step.durationDays??index);return Math.max(0,Math.min(totalDays,Math.round(raw/maxTemplate*totalDays)));}
function parseChecklistSelections(context:any){return Array.isArray(context?.checklistSelections)?context.checklistSelections.filter((item:any)=>Array.isArray(item?.items)&&item.items.length):[];}
function stageMatches(title:string,target:string){const a=title.toLowerCase(),b=target.toLowerCase();return a.includes(b)||b.includes(a)||(/photo/.test(a)&&/photo/.test(b));}
function taskDescription(step:ApprovalStep){const text=String(step.description||"").trim();return step.requiresFiles?`${text}${text?"\n\n":""}__UPZ_REQUIRES_FILES__`:text||null;}

export async function POST(request:NextRequest,context:{params:Promise<{id:string}>}){try{const{id}=await context.params;const requestId=Number(id);const body=await request.json().catch(()=>({}));if(!Number.isInteger(requestId)||requestId<=0)return NextResponse.json({error:"Invalid request id"},{status:400});const source=await prisma.marketingRequest.findUnique({where:{id:requestId}});if(!source)return NextResponse.json({error:"Request not found"},{status:404});const existingProject=await prisma.project.findUnique({where:{requestId:source.id}});if(existingProject)return NextResponse.json(existingProject);const parsed=parseRequestDescription(source.description);const stored=parsed.context||{};const workflow=approvalStages(body?.stages,getWorkflowTemplate(source.type||source.title));const startDate=body?.startDate?new Date(`${body.startDate}T12:00:00`):new Date();const dueDate=body?.dueDate?new Date(`${body.dueDate}T12:00:00`):new Date(startDate.getTime()+Math.max(...workflow.map(step=>step.durationDays||0),7)*86400000);if(dueDate<startDate)return NextResponse.json({error:"Overall due date must be on or after the start date"},{status:400});const requestedProjectId=body?.engagementId?Number(body.engagementId):stored.engagementId?Number(stored.engagementId):null;const projectName=String(body?.engagementName||body?.portfolioName||stored.portfolioName||stored.engagementName||"").trim();const propertyAddress=String(body?.propertyAddress||stored.propertyAddress||"").trim();const locationName=String(body?.locationName||stored.locationName||"").trim();const projectManager=body?.assignedTo?String(body.assignedTo).trim():null;const title=String(body?.title||source.title||`${projectName} · ${locationName||"Work Order"} · ${source.type}`).trim();const checklistSelections=parseChecklistSelections(stored);
 const project=await prisma.$transaction(async tx=>{let parent=requestedProjectId?await tx.engagement.findFirst({where:{id:requestedProjectId,companyId:source.companyId}}):null;if(!parent){if(!projectName)throw new Error("Project name is required");const baseSlug=slugify(projectName);parent=await tx.engagement.findFirst({where:{companyId:source.companyId,OR:[{slug:baseSlug},{name:{equals:projectName,mode:"insensitive"}}]}});if(!parent){let uniqueSlug=baseSlug,suffix=2;while(await tx.engagement.findUnique({where:{companyId_slug:{companyId:source.companyId,slug:uniqueSlug}}}))uniqueSlug=`${baseSlug}-${suffix++}`;parent=await tx.engagement.create({data:{companyId:source.companyId,name:projectName,slug:uniqueSlug,type:String(body?.engagementType||stored.engagementType||(propertyAddress?"property":"portfolio")),address:propertyAddress||null,description:locationName?`Project containing work orders for locations and assets including ${locationName}.`:null}});}else if(propertyAddress&&!parent.address){parent=await tx.engagement.update({where:{id:parent.id},data:{address:propertyAddress}});}}
  const created=await tx.project.create({data:{companyId:source.companyId,engagementId:parent.id,requestId:source.id,packageId:stored.packageId?Number(stored.packageId):null,title,description:parsed.description,status:"new",priority:String(body?.priority||source.priority||"normal"),assignedTo:projectManager,startDate,dueDate,clientVisible:body?.clientVisible===undefined?true:Boolean(body.clientVisible),activities:{create:[{type:"project_created",message:`Work order created inside project ${parent.name} with ${workflow.length} approved stages.`,actor:"UPZ Admin"},{type:"assignment_changed",message:projectManager?`Project manager: ${projectManager}.`:"Work order created without a project manager.",actor:"UPZ Admin"},{type:"schedule_created",message:`Overall schedule: ${startDate.toLocaleDateString("en-US")} to ${dueDate.toLocaleDateString("en-US")}.`,actor:"UPZ Admin"}]}}});
  for(let index=0;index<workflow.length;index++){const step=workflow[index];const taskDueDate=new Date(startDate);taskDueDate.setDate(taskDueDate.getDate()+scaledOffset(step,index,workflow,startDate,dueDate));const checklist=checklistSelections.filter((selection:any)=>stageMatches(step.title,String(selection.stage||""))).flatMap((selection:any)=>selection.items.map((item:string)=>String(item).trim())).filter(Boolean);await tx.projectTask.create({data:{projectId:created.id,title:step.title,description:taskDescription(step),status:index===0?"in_progress":"blocked",priority:source.priority||"normal",assignedTo:step.assignedTo||projectManager,dueDate:taskDueDate,sortOrder:index,checklist:checklist.length?{create:checklist.map((item:string,sortOrder:number)=>({title:item,sortOrder}))}:undefined}});}
  await tx.marketingRequest.update({where:{id:source.id},data:{status:"approved"}});return created;});return NextResponse.json(project,{status:201});}catch(error:any){console.error("Convert request error:",error);if(error?.code==="P2002"){const{id}=await context.params;const existing=await prisma.project.findUnique({where:{requestId:Number(id)}});if(existing)return NextResponse.json(existing);}return NextResponse.json({error:error?.message||"Unable to create work order"},{status:500});}}
