"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Project={id:number;title:string;status:string;priority:string;assignedTo?:string|null;dueDate?:string|null;company:{name:string;shortName:string}};
type Task={id:number;projectId:number;title:string;status:string;priority:string;assignedTo?:string|null;dueDate?:string|null;project:{title:string;company:{shortName:string}}};
type Member={id:number;name:string;email?:string|null;role:string;capacity:number;active:boolean;assignedProjects:Project[];assignedTasks:Task[];workload:{projects:number;tasks:number;openTasks:number;remainingCapacity:number}};
type ManagementData={members:Member[];projects:Project[];tasks:Task[]};
const emptyForm={name:"",email:"",role:"Creative Operations",capacity:"5"};
const pretty=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function TeamPage(){
 const[data,setData]=useState<ManagementData|null>(null);const[form,setForm]=useState(emptyForm);const[edit,setEdit]=useState(emptyForm);const[editingId,setEditingId]=useState<number|null>(null);const[expandedId,setExpandedId]=useState<number|null>(null);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[query,setQuery]=useState("");const[status,setStatus]=useState("active");const[assignType,setAssignType]=useState<"task"|"project">("task");const[assignment,setAssignment]=useState<Record<number,string>>({});
 async function load(){const response=await fetch("/api/admin/team/management",{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value?.error||"Unable to load team");setData(value)}
 useEffect(()=>{load().catch(error=>setMessage(error.message))},[]);
 async function request(url:string,options:RequestInit){setSaving(true);setMessage("");try{const response=await fetch(url,options);const value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value?.error||"Request failed");await load();return true}catch(error:any){setMessage(error.message||"Request failed");return false}finally{setSaving(false)}}
 async function add(e:FormEvent){e.preventDefault();const ok=await request("/api/admin/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,capacity:Number(form.capacity)})});if(ok)setForm(emptyForm)}
 function startEdit(member:Member){setEditingId(member.id);setEdit({name:member.name,email:member.email||"",role:member.role,capacity:String(member.capacity)})}
 async function save(member:Member){const ok=await request(`/api/admin/team/${member.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...edit,capacity:Number(edit.capacity)})});if(ok)setEditingId(null)}
 async function toggle(member:Member){await request(`/api/admin/team/${member.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!member.active})})}
 async function remove(member:Member){if(!confirm(`Remove ${member.name}? Their ${member.workload.projects} projects and ${member.workload.tasks} tasks will be unassigned.`))return;await request(`/api/admin/team/${member.id}`,{method:"DELETE"})}
 async function assign(member:Member){const recordId=Number(assignment[member.id]);if(!recordId)return;const ok=await request(`/api/admin/team/${member.id}/assignments`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:assignType,action:"assign",recordId})});if(ok)setAssignment(current=>({...current,[member.id]:""}))}
 async function unassign(member:Member,type:"task"|"project",recordId:number){await request(`/api/admin/team/${member.id}/assignments`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,action:"unassign",recordId})})}
 const members=useMemo(()=>!data?[]:data.members.filter(member=>{const match=`${member.name} ${member.email||""} ${member.role}`.toLowerCase().includes(query.toLowerCase());return match&&(status==="all"||status==="active"&&member.active||status==="inactive"&&!member.active)}),[data,query,status]);
 if(!data)return <main className="team-management-page"><section className="admin-simple-state"><h1>Loading team workspace...</h1></section></main>;
 const active=data.members.filter(m=>m.active).length;const openTasks=data.members.reduce((sum,m)=>sum+m.workload.openTasks,0);const unassignedTasks=data.tasks.filter(t=>!t.assignedTo&&t.status!=="complete");const unassignedProjects=data.projects.filter(p=>!p.assignedTo&&!['complete','completed','archived'].includes(p.status));
 return <main className="team-management-page"><header className="team-management-hero"><div><span>UPZ OPERATIONS</span><h1>Team Management</h1><p>Add contributors, manage access status, review workload, and assign or unassign projects and tasks.</p></div><div className="team-summary"><article><small>Active team</small><strong>{active}</strong></article><article><small>Open assignments</small><strong>{openTasks}</strong></article><article><small>Unassigned tasks</small><strong>{unassignedTasks.length}</strong></article></div></header>
 {message&&<div className="team-alert">{message}</div>}
 <section className="team-create-panel"><div><h2>Add team member</h2><p>The email becomes their contributor login identity.</p></div><form onSubmit={add}><input required placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="email" required placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required placeholder="Role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><input type="number" min="1" required placeholder="Capacity" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/><button disabled={saving}>Add Member</button></form></section>
 <div className="team-toolbar"><input placeholder="Search people..." value={query} onChange={e=>setQuery(e.target.value)}/><nav>{["active","inactive","all"].map(value=><button type="button" key={value} className={status===value?"active":""} onClick={()=>setStatus(value)}>{pretty(value)}</button>)}</nav></div>
 <section className="team-management-list">{members.map(member=>{const expanded=expandedId===member.id;const options=assignType==="task"?unassignedTasks:unassignedProjects;return <article className={`team-management-card ${member.active?"active":"inactive"}`} key={member.id}><div className="team-card-main"><div className="team-avatar">{member.name.split(" ").map(p=>p[0]).join("").slice(0,2)}</div>{editingId===member.id?<div className="team-inline-edit"><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/><input type="email" value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/><input value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}/><input type="number" min="1" value={edit.capacity} onChange={e=>setEdit({...edit,capacity:e.target.value})}/></div>:<div className="team-identity"><div><h2>{member.name}</h2><span className={member.active?"member-status active":"member-status"}>{member.active?"Active":"Inactive"}</span></div><p>{member.role}</p><small>{member.email||"No email configured"}</small></div>}<div className="team-workload"><div><small>Projects</small><strong>{member.workload.projects}</strong></div><div><small>Open tasks</small><strong>{member.workload.openTasks}/{member.capacity}</strong></div><div><small>Available</small><strong>{member.workload.remainingCapacity}</strong></div></div></div>
 <div className="team-card-controls">{editingId===member.id?<><button onClick={()=>save(member)} disabled={saving}>Save</button><button className="secondary" onClick={()=>setEditingId(null)}>Cancel</button></>:<><button onClick={()=>setExpandedId(expanded?null:member.id)}>{expanded?"Close Assignments":"Manage Assignments"}</button><button className="secondary" onClick={()=>startEdit(member)}>Edit</button><button className="secondary" onClick={()=>toggle(member)} disabled={saving}>{member.active?"Deactivate":"Activate"}</button><button className="danger" onClick={()=>remove(member)} disabled={saving}>Remove</button></>}</div>
 {expanded&&<div className="team-assignment-workspace"><section className="team-assign-new"><div><h3>Assign work</h3><p>Choose an unassigned project or task.</p></div><select value={assignType} onChange={e=>setAssignType(e.target.value as "task"|"project")}><option value="task">Task</option><option value="project">Project</option></select><select value={assignment[member.id]||""} onChange={e=>setAssignment(current=>({...current,[member.id]:e.target.value}))}><option value="">Select {assignType}</option>{options.map(item=><option key={item.id} value={item.id}>{'project' in item?`${item.project.company.shortName} · ${item.project.title} · ${item.title}`:`${item.company.shortName} · ${item.title}`}</option>)}</select><button onClick={()=>assign(member)} disabled={!assignment[member.id]||saving}>Assign</button></section><div className="team-assignment-columns"><section><h3>Assigned projects <span>{member.assignedProjects.length}</span></h3>{member.assignedProjects.length?member.assignedProjects.map(project=><div className="team-assignment-row" key={project.id}><div><small>{project.company.shortName} · {pretty(project.status)}</small><strong>{project.title}</strong></div><button onClick={()=>unassign(member,"project",project.id)}>Unassign</button></div>):<p className="team-empty">No assigned projects.</p>}</section><section><h3>Assigned tasks <span>{member.assignedTasks.length}</span></h3>{member.assignedTasks.length?member.assignedTasks.map(task=><div className="team-assignment-row" key={task.id}><div><small>{task.project.company.shortName} · {task.project.title}</small><strong>{task.title}</strong><em>{pretty(task.status)}</em></div><button onClick={()=>unassign(member,"task",task.id)}>Unassign</button></div>):<p className="team-empty">No assigned tasks.</p>}</section></div></div>}</article>})}{!members.length&&<div className="team-empty-state"><h2>No team members found</h2><p>Adjust the filter or add a new contributor.</p></div>}</section></main>;
}
