"use client";

import { FormEvent, useEffect, useState } from "react";

type Member = { id:number; name:string; email?:string|null; role:string; capacity:number; active:boolean };

export default function TeamPage(){
 const [members,setMembers]=useState<Member[]>([]);const [form,setForm]=useState({name:"",email:"",role:"Creative Operations",capacity:"5"});const [savingId,setSavingId]=useState<number|null>(null);const [editingId,setEditingId]=useState<number|null>(null);const [edit,setEdit]=useState({name:"",email:"",role:"",capacity:"5"});const [message,setMessage]=useState("");
 const load=()=>fetch("/api/admin/team",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Unable to load team");return r.json()}).then(data=>setMembers(Array.isArray(data)?data:[]));
 useEffect(()=>{load().catch(error=>setMessage(error?.message||"Unable to load team"))},[]);
 async function add(e:FormEvent){e.preventDefault();setMessage("");const response=await fetch("/api/admin/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,capacity:Number(form.capacity)})});if(!response.ok){setMessage("Unable to add team member");return}setForm({name:"",email:"",role:"Creative Operations",capacity:"5"});await load()}
 async function patch(member:Member,body:Record<string,unknown>){if(savingId)return;setSavingId(member.id);setMessage("");try{const response=await fetch(`/api/admin/team/${member.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error("Unable to update team member");await load()}catch(error:any){setMessage(error?.message||"Unable to update team member")}finally{setSavingId(null)}}
 async function toggle(member:Member){await patch(member,{active:!member.active})}
 function startEdit(member:Member){setEditingId(member.id);setEdit({name:member.name,email:member.email||"",role:member.role,capacity:String(member.capacity)})}
 async function saveEdit(member:Member){await patch(member,{...edit,capacity:Number(edit.capacity)});setEditingId(null)}
 async function remove(member:Member){if(!window.confirm(`Remove ${member.name} from the team directory?`))return;setSavingId(member.id);const response=await fetch(`/api/admin/team/${member.id}`,{method:"DELETE"});setSavingId(null);if(!response.ok){setMessage("Unable to remove team member");return}await load()}
 return <main className="ops-page"><header className="ops-head"><div><span>UPZ WORKSPACE</span><h1>Team Directory</h1><p>Create and manage the people available for work-order and task assignment.</p></div></header>{message&&<p className="admin-error">{message}</p>}<form className="team-form" onSubmit={add}><input required placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Role" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><input type="number" min="1" placeholder="Capacity" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/><button type="submit">Add team member</button></form><section className="ops-grid">{members.map(member=><article className={`ops-panel team-member-card ${member.active?"is-active":"is-inactive"}`} key={member.id}><div className="ops-avatar">{member.name.split(" ").map(p=>p[0]).join("").slice(0,2)}</div>{editingId===member.id?<div className="team-edit-form"><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/><input value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/><input value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}/><input type="number" min="1" value={edit.capacity} onChange={e=>setEdit({...edit,capacity:e.target.value})}/></div>:<><h3>{member.name}</h3><p>{member.role}</p><dl><div><dt>Email</dt><dd>{member.email||"—"}</dd></div><div><dt>Capacity</dt><dd>{member.capacity}</dd></div><div><dt>Status</dt><dd>{member.active?"Active":"Inactive"}</dd></div></dl></>}<div className="team-card-actions">{editingId===member.id?<><button type="button" onClick={()=>saveEdit(member)} disabled={savingId===member.id}>Save</button><button type="button" onClick={()=>setEditingId(null)}>Cancel</button></>:<><button type="button" onClick={()=>startEdit(member)}>Edit</button><button type="button" className={member.active?"team-deactivate-button":"team-activate-button"} disabled={savingId===member.id} onClick={()=>toggle(member)}>{savingId===member.id?"Saving...":member.active?"Deactivate":"Activate"}</button><button type="button" className="admin-danger-button" onClick={()=>remove(member)} disabled={savingId===member.id}>Remove</button></>}</div></article>)}</section></main>
}
