"use client";

import Link from "next/link";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {useParams} from "next/navigation";
import {parseProjectMessage} from "@/lib/project-messages";
import {PROJECT_STAGES,normalizeProjectStage} from "@/lib/project-status";

type Task={id:number;title:string;description?:string|null;status:string;priority:string;assignedTo?:string|null;dueDate?:string|null;sortOrder:number};
type Note={id:number;body:string;visibility:string;author?:string|null;createdAt:string};
type Activity={id:number;type:string;message:string;actor?:string|null;createdAt:string};
type Project={id:number;title:string;description?:string|null;status:string;priority:string;assignedTo?:string|null;startDate?:string|null;dueDate?:string|null;budget?:number|null;internalCost?:number|null;clientVisible:boolean;company:{name:string;shortName:string;slug:string;logo?:string|null;primaryColor:string};engagement?:{id:number;name:string;address?:string|null}|null;request?:{id:number;type:string}|null;tasks:Task[];notes:Note[];activities:Activity[]};
type Deliverable={id:number;projectId:number;title:string;description?:string|null;status:string;category:string;versions:Array<{id:number;versionNumber:number;label?:string|null;fileUrl:string;fileName?:string|null;status:string}>};
type TeamMember={id:number;name:string;role:string};
const TABS=["overview","tasks","files","messages","activity","team"] as const;type Tab=typeof TABS[number];
const dateValue=(value?:string|null)=>value?new Date(value).toISOString().slice(0,10):"";
const pretty=(value:string)=>value.replaceAll("_"," ").replaceAll("-"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function ProjectWorkspacePage(){
 const params=useParams();const id=Number(Array.isArray(params?.id)?params.id[0]:params?.id);
 const[project,setProject]=useState<Project|null>(null);const[files,setFiles]=useState<Deliverable[]>([]);const[team,setTeam]=useState<TeamMember[]>([]);const[tab,setTab]=useState<Tab>("overview");const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[note,setNote]=useState("");const[noteType,setNoteType]=useState("internal");const[newTask,setNewTask]=useState("");const[saving,setSaving]=useState(false);
 async function load(){if(!id)return;setLoading(true);try{const[p,d,o]=await Promise.all([fetch(`/api/admin/projects/${id}`,{cache:"no-store"}),fetch("/api/admin/deliverables",{cache:"no-store"}),fetch("/api/admin/operations",{cache:"no-store"})]);if(!p.ok)throw new Error("Unable to load project workspace");const projectData=await p.json();setProject({...projectData,status:normalizeProjectStage(projectData.status),tasks:[...(projectData.tasks||[])].sort((a:Task,b:Task)=>a.sortOrder-b.sortOrder)});setFiles(d.ok?(await d.json()).filter((item:Deliverable)=>item.projectId===id):[]);const operations=o.ok?await o.json():null;setTeam(Array.isArray(operations?.team)?operations.team:[]);}catch(error:any){setMessage(error?.message||"Unable to load project workspace");}finally{setLoading(false)}}
 useEffect(()=>{load()},[id]);
 const done=useMemo(()=>project?.tasks.filter(task=>["complete","completed"].includes(task.status)).length||0,[project]);const progress=project?.tasks.length?Math.round(done/project.tasks.length*100):0;
 async function patchProject(body:Record<string,unknown>){if(!project)return;setSaving(true);const response=await fetch(`/api/admin/projects/${project.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setSaving(false);if(response.ok){setProject(await response.json());setMessage("Project updated.")}else setMessage("Unable to update project.")}
 async function patchTask(task:Task,body:Record<string,unknown>){await fetch(`/api/admin/tasks/${task.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});await load()}
 async function addTask(event:FormEvent){event.preventDefault();if(!project||!newTask.trim())return;await fetch(`/api/admin/work-orders/${project.id}/tasks`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:newTask.trim()})});setNewTask("");await load()}
 async function postNote(event:FormEvent){event.preventDefault();if(!project||!note.trim())return;setSaving(true);const response=await fetch(`/api/admin/projects/${project.id}/notes`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:note.trim(),kind:noteType,author:"UPZ Admin"})});setSaving(false);if(response.ok){setNote("");await load()}else setMessage("Unable to post update.")}
 if(loading)return <main className="admin-page project-os-page"><section className="admin-simple-state"><h1>Loading project workspace...</h1></section></main>;
 if(!project)return <main className="admin-page project-os-page"><section className="admin-simple-state"><h1>Project not found</h1><p>{message}</p></section></main>;
 const style={"--project-brand":project.company.primaryColor} as React.CSSProperties;
 return <main className="admin-page project-os-page" style={style}><section className="project-os-shell">
  <header className="project-os-hero"><div className="project-os-brand"><div className="project-os-logo"><img src={project.company.logo||"/upz-logo.svg"} alt=""/></div><div><span>Project Workspace</span><h1>{project.title}</h1><p>{project.company.name}{project.engagement?.name?` · ${project.engagement.name}`:""}</p></div></div><div className="project-os-hero-actions"><Link href="/admin/operations">Operations</Link><Link href={`/portal/${project.company.slug}/projects#engagement-${project.engagement?.id||""}`}>Client View</Link></div></header>
  <section className="project-os-summary"><article><small>Status</small><strong>{pretty(project.status)}</strong></article><article><small>Progress</small><strong>{progress}%</strong></article><article><small>Project Manager</small><strong>{project.assignedTo||"Unassigned"}</strong></article><article><small>Due</small><strong>{project.dueDate?new Date(project.dueDate).toLocaleDateString():"Not set"}</strong></article><article><small>Files</small><strong>{files.length}</strong></article></section>
  <nav className="project-os-tabs">{TABS.map(value=><button key={value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{pretty(value)}{value==="tasks"&&<span>{project.tasks.length}</span>}{value==="files"&&<span>{files.length}</span>}</button>)}</nav>
  {message&&<p className="project-os-message">{message}</p>}
  {tab==="overview"&&<section className="project-os-grid"><article className="project-os-panel project-os-brief"><span>Project Brief</span><h2>Overview</h2><p>{project.description||"No project description has been added yet."}</p><div className="project-os-progress"><div><strong>Production progress</strong><span>{done} of {project.tasks.length} tasks complete</span></div><i><b style={{width:`${progress}%`}}/></i></div></article><article className="project-os-panel"><span>Project Settings</span><h2>Management</h2><div className="project-os-form-grid"><label>Status<select value={project.status} onChange={e=>patchProject({status:e.target.value})}>{PROJECT_STAGES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Priority<select value={project.priority} onChange={e=>patchProject({priority:e.target.value})}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Project manager<select value={project.assignedTo||""} onChange={e=>patchProject({assignedTo:e.target.value})}><option value="">Unassigned</option>{team.map(member=><option key={member.id} value={member.name}>{member.name} — {member.role}</option>)}</select></label><label>Due date<input type="date" value={dateValue(project.dueDate)} onChange={e=>patchProject({dueDate:e.target.value})}/></label></div><label className="project-os-check"><input type="checkbox" checked={project.clientVisible} onChange={e=>patchProject({clientVisible:e.target.checked})}/> Visible in client workspace</label></article><article className="project-os-panel project-os-recent"><span>Recent Activity</span><h2>Latest updates</h2>{project.activities.slice(0,6).map(activity=><div key={activity.id}><i/><p><strong>{activity.message}</strong><small>{activity.actor||"System"} · {new Date(activity.createdAt).toLocaleString()}</small></p></div>)}</article></section>}
  {tab==="tasks"&&<section className="project-os-panel project-os-task-panel"><div className="project-os-section-head"><div><span>Production</span><h2>Tasks</h2></div><strong>{done}/{project.tasks.length} completed</strong></div><div className="project-os-task-list">{project.tasks.map((task,index)=><article key={task.id}><button className={["complete","completed"].includes(task.status)?"done":""} onClick={()=>patchTask(task,{status:["complete","completed"].includes(task.status)?"todo":"complete"})}>{["complete","completed"].includes(task.status)?"✓":"○"}</button><div><strong>{task.title}</strong>{task.description&&<p>{task.description}</p>}<small>{index+1}. {pretty(task.status)}</small></div><select value={task.assignedTo||""} onChange={e=>patchTask(task,{assignedTo:e.target.value})}><option value="">Unassigned</option>{team.map(member=><option key={member.id}>{member.name}</option>)}</select><input type="date" value={dateValue(task.dueDate)} onChange={e=>patchTask(task,{dueDate:e.target.value})}/></article>)}</div><form className="project-os-add-task" onSubmit={addTask}><input value={newTask} onChange={e=>setNewTask(e.target.value)} placeholder="Add another project task..."/><button>Add Task</button></form></section>}
  {tab==="files"&&<section className="project-os-panel"><div className="project-os-section-head"><div><span>Project Outputs</span><h2>Files & Deliverables</h2></div><Link href={`/admin/deliverables?project=${project.id}`}>Publish File</Link></div>{files.length?<div className="project-os-file-grid">{files.map(file=>{const current=file.versions?.[0];return <article key={file.id}><span>{pretty(file.category)}</span><h3>{file.title}</h3><p>{file.description||"Project file"}</p><div><strong>{pretty(file.status)}</strong>{current&&<a href={current.fileUrl} target="_blank" rel="noreferrer">Open {current.fileName||`Version ${current.versionNumber}`} ↗</a>}</div></article>})}</div>:<div className="project-os-empty"><h3>No project files yet</h3><p>Publish project outputs here when they are ready for internal use or client review.</p><Link href={`/admin/deliverables?project=${project.id}`}>Add First File</Link></div>}</section>}
  {tab==="messages"&&<section className="project-os-panel project-os-messages"><div className="project-os-section-head"><div><span>Communication</span><h2>Updates & Messages</h2></div></div><form onSubmit={postNote}><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Write an internal note, client update, feedback request, or approval request..."/><div><select value={noteType} onChange={e=>setNoteType(e.target.value)}><option value="internal">Internal note</option><option value="client_update">Client update</option><option value="feedback_request">Request client feedback</option><option value="approval_request">Request client approval</option></select><button disabled={saving}>{saving?"Posting...":"Post Update"}</button></div></form><div className="project-os-thread">{project.notes.map(item=>{const parsed=parseProjectMessage(item.body);const client=parsed.kind==="client_response";return <article key={item.id} className={client?"client-response":item.visibility==="client"?"client-visible":"internal"}><div><strong>{client?"Client Response":item.visibility==="client"?"Client Update":"Internal Note"}</strong><small>{item.author||"UPZ Admin"} · {new Date(item.createdAt).toLocaleString()}</small></div><p>{parsed.body}</p></article>})}</div></section>}
  {tab==="activity"&&<section className="project-os-panel"><div className="project-os-section-head"><div><span>Timeline</span><h2>Project Activity</h2></div></div><div className="project-os-timeline">{project.activities.map(activity=><article key={activity.id}><i/><div><span>{pretty(activity.type)}</span><strong>{activity.message}</strong><small>{activity.actor||"System"} · {new Date(activity.createdAt).toLocaleString()}</small></div></article>)}</div></section>}
  {tab==="team"&&<section className="project-os-panel"><div className="project-os-section-head"><div><span>Assignments</span><h2>Project Team</h2></div></div><div className="project-os-team-grid"><article><span>Project Manager</span><h3>{project.assignedTo||"Unassigned"}</h3><p>Owns the complete project and client relationship.</p></article>{Array.from(new Set(project.tasks.map(task=>task.assignedTo).filter(Boolean))).map(name=><article key={name}><span>Task Contributor</span><h3>{name}</h3><p>{project.tasks.filter(task=>task.assignedTo===name).length} assigned task(s)</p></article>)}</div></section>}
 </section></main>
}