"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { AdminButton, AdminCard, AdminEmptyState, AdminFormGrid, AdminField, AdminHeader, AdminPage, AdminSection, AdminSectionHeader, AdminStats, AdminTabs, StatCard } from "@/components/admin/AdminUI";

type Intelligence={propertyType?:string;buildingClass?:string;neighborhood?:string;borough?:string;owner?:string;landlord?:string;tenant?:string;brokerage?:string;squareFootage?:string;floors?:string;frontage?:string;ceilingHeight?:string;accessRestrictions?:string;loading?:string;parking?:string;latitude?:string;longitude?:string;marketingStatus?:string;notes?:string};
type Property={id:number;name:string;type:string;status:string;address?:string|null;city?:string|null;state?:string|null;postalCode?:string|null;description?:string|null;intelligence:Intelligence;intelligenceCompleteness:number;progress:number;company:{name:string;shortName:string;slug:string;primaryColor:string};assets:Array<{id:number;title:string;category:string;fileUrl?:string|null;description?:string|null}>;workOrders:Array<{id:number;title:string;status:string;priority:string;assignedTo?:string|null;dueDate?:string|null;tasks:Array<{id:number;status:string}>}>};
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function PropertyIntelligencePage(){
 const params=useParams(),id=Array.isArray(params?.id)?params.id[0]:params?.id;
 const[data,setData]=useState<Property|null>(null),[draft,setDraft]=useState<any>(null),[tab,setTab]=useState("profile"),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 async function load(){if(!id)return;const response=await fetch(`/api/admin/engagements/${id}`,{cache:"no-store"});const value=await response.json();if(response.ok){setData(value);setDraft({name:value.name,address:value.address||"",city:value.city||"",state:value.state||"",postalCode:value.postalCode||"",description:value.description||"",intelligence:value.intelligence||{}})}else setMessage(value.error||"Unable to load property")}
 useEffect(()=>{load()},[id]);
 async function save(){if(!data||!draft)return;setSaving(true);setMessage("");const response=await fetch(`/api/admin/engagements/${data.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const value=await response.json().catch(()=>({}));setSaving(false);if(!response.ok)return setMessage(value.error||"Unable to save property");setMessage("Property intelligence saved.");await load()}
 const updateIntel=(key:keyof Intelligence,value:string)=>setDraft((current:any)=>({...current,intelligence:{...current.intelligence,[key]:value}}));
 if(!data||!draft)return <AdminPage><AdminEmptyState>{message||"Loading Property Intelligence..."}</AdminEmptyState></AdminPage>;
 const active=data.workOrders.filter(order=>!["complete","completed","archived","cancelled"].includes(order.status.toLowerCase())).length;
 return <AdminPage className="property-intelligence-page"><AdminHeader eyebrow={`${data.company.shortName} · Property Intelligence`} title={data.name} description={[data.address,data.city,data.state,data.postalCode].filter(Boolean).join(", ")||"Build the permanent property record that powers future services, pricing, and generated content."} actions={<><AdminButton variant="outline" href="/admin/properties">All Properties</AdminButton><AdminButton variant="outline" href={`/admin/projects/${data.id}`}>Project View</AdminButton><AdminButton href={`/portal/${data.company.slug}/request/general?engagementId=${data.id}&engagementName=${encodeURIComponent(data.name)}`}>Add Request</AdminButton></>}/>
 {message&&<div className="admin-ui-notice-inline">{message}</div>}
 <AdminStats><StatCard label="Intelligence profile" value={`${data.intelligenceCompleteness}%`}/><StatCard label="Active work" value={active}/><StatCard label="Reusable assets" value={data.assets.length}/><StatCard label="Production progress" value={`${data.progress}%`}/></AdminStats>
 <AdminTabs>{[["profile","Property Profile"],["assets","Asset Library"],["work","Services & Work"],["opportunities","Opportunities"]].map(([value,title])=><button type="button" key={value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{title}</button>)}</AdminTabs>
 {tab==="profile"&&<><AdminSection><AdminSectionHeader eyebrow="Core Identity" title="Property information" actions={<AdminButton type="button" onClick={save} disabled={saving}>{saving?"Saving...":"Save Property"}</AdminButton>}/><AdminFormGrid><AdminField label="Property name"><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></AdminField><AdminField label="Property type"><input value={draft.intelligence.propertyType||""} onChange={e=>updateIntel("propertyType",e.target.value)} placeholder="Retail, office, mixed-use..."/></AdminField><AdminField label="Street address" className="wide"><input value={draft.address} onChange={e=>setDraft({...draft,address:e.target.value})}/></AdminField><AdminField label="City"><input value={draft.city} onChange={e=>setDraft({...draft,city:e.target.value})}/></AdminField><AdminField label="State"><input value={draft.state} onChange={e=>setDraft({...draft,state:e.target.value})}/></AdminField><AdminField label="ZIP"><input value={draft.postalCode} onChange={e=>setDraft({...draft,postalCode:e.target.value})}/></AdminField><AdminField label="Borough"><input value={draft.intelligence.borough||""} onChange={e=>updateIntel("borough",e.target.value)}/></AdminField><AdminField label="Neighborhood"><input value={draft.intelligence.neighborhood||""} onChange={e=>updateIntel("neighborhood",e.target.value)}/></AdminField><AdminField label="Building class"><input value={draft.intelligence.buildingClass||""} onChange={e=>updateIntel("buildingClass",e.target.value)}/></AdminField></AdminFormGrid></AdminSection>
 <AdminSection><AdminSectionHeader eyebrow="CRE Context" title="Ownership, leasing, and physical details"/><AdminFormGrid><AdminField label="Owner"><input value={draft.intelligence.owner||""} onChange={e=>updateIntel("owner",e.target.value)}/></AdminField><AdminField label="Landlord"><input value={draft.intelligence.landlord||""} onChange={e=>updateIntel("landlord",e.target.value)}/></AdminField><AdminField label="Tenant"><input value={draft.intelligence.tenant||""} onChange={e=>updateIntel("tenant",e.target.value)}/></AdminField><AdminField label="Brokerage"><input value={draft.intelligence.brokerage||""} onChange={e=>updateIntel("brokerage",e.target.value)}/></AdminField><AdminField label="Square footage"><input value={draft.intelligence.squareFootage||""} onChange={e=>updateIntel("squareFootage",e.target.value)}/></AdminField><AdminField label="Floors / spaces"><input value={draft.intelligence.floors||""} onChange={e=>updateIntel("floors",e.target.value)}/></AdminField><AdminField label="Frontage"><input value={draft.intelligence.frontage||""} onChange={e=>updateIntel("frontage",e.target.value)}/></AdminField><AdminField label="Ceiling height"><input value={draft.intelligence.ceilingHeight||""} onChange={e=>updateIntel("ceilingHeight",e.target.value)}/></AdminField><AdminField label="Access restrictions" className="wide"><textarea value={draft.intelligence.accessRestrictions||""} onChange={e=>updateIntel("accessRestrictions",e.target.value)}/></AdminField><AdminField label="Loading / freight"><input value={draft.intelligence.loading||""} onChange={e=>updateIntel("loading",e.target.value)}/></AdminField><AdminField label="Parking / traffic notes"><input value={draft.intelligence.parking||""} onChange={e=>updateIntel("parking",e.target.value)}/></AdminField><AdminField label="Property summary" className="wide"><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></AdminField></AdminFormGrid></AdminSection></>}
 {tab==="assets"&&<AdminSection><AdminSectionHeader eyebrow="Reusable Knowledge" title="Property Asset Library"/><p>Completed work automatically contributes reusable files here. Future brochure, website, social, rendering, and AI tools will pull from this library.</p><div className="property-asset-library">{data.assets.map(asset=><AdminCard key={asset.id}><span className="admin-ui-eyebrow">{asset.category}</span><h3>{asset.title}</h3><p>{asset.description||"Reusable property asset"}</p>{asset.fileUrl&&<a href={asset.fileUrl} target="_blank" rel="noreferrer">Open asset →</a>}</AdminCard>)}{!data.assets.length&&<AdminEmptyState>No reusable assets yet. Completing file-producing work will populate this library.</AdminEmptyState>}</div></AdminSection>}
 {tab==="work"&&<AdminSection><AdminSectionHeader eyebrow="Production Network" title="Services and work orders"/><div className="property-work-list">{data.workOrders.map(order=><AdminCard key={order.id}><span className="admin-ui-eyebrow">{label(order.status)} · {order.priority}</span><h3>{order.title}</h3><p>{order.assignedTo||"Unassigned"}{order.dueDate?` · due ${new Date(order.dueDate).toLocaleDateString()}`:""}</p><AdminButton href={`/admin/project/${order.id}`}>Open Workspace</AdminButton></AdminCard>)}{!data.workOrders.length&&<AdminEmptyState>No work orders yet.</AdminEmptyState>}</div></AdminSection>}
 {tab==="opportunities"&&<AdminSection><AdminSectionHeader eyebrow="Future Intelligence" title="Marketing opportunities"/><div className="property-opportunity-grid">{["Generate leasing brochure","Create social media campaign","Build property website","Generate retail map","Create email campaign","Enhance or stage photography"].map(title=><AdminCard key={title}><span className="admin-ui-eyebrow">Coming next</span><h3>{title}</h3><p>This recommendation will use the property profile and existing reusable assets to minimize repeated client input.</p></AdminCard>)}</div></AdminSection>}
 </AdminPage>
}
