"use client";

import type { CSSProperties } from "react";
type Task={id:number;title:string;status:string;assignedTo?:string|null;dueDate?:string|null;sortOrder?:number};
type Project={id:number;title:string;status:string;priority:string;assignedTo?:string|null;startDate?:string|null;dueDate?:string|null;company:{shortName:string;primaryColor?:string|null};engagement?:{name:string}|null;tasks:Task[]};
type Member={id:number;name:string;role:string;capacity:number;active:number;overdue:number;tasks:number};type Props={projects:Project[];team:Member[];onOpen:(project:any)=>void};
const DAY=86400000,startOfDay=(value:Date)=>new Date(value.getFullYear(),value.getMonth(),value.getDate()),addDays=(value:Date,days:number)=>new Date(value.getTime()+days*DAY),monday=(value:Date)=>{const date=startOfDay(value),day=date.getDay()||7;return addDays(date,1-day)};
const taskDone=(task:Task)=>["complete","completed"].includes(String(task.status).toLowerCase());
const sortedTasks=(project:Project)=>[...project.tasks].sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0));
const taskBlocked=(project:Project,task:Task)=>{const tasks=sortedTasks(project),index=tasks.findIndex(item=>item.id===task.id);return index>0&&!taskDone(tasks[index-1]);};
const projectStart=(project:Project,today:Date)=>project.startDate?startOfDay(new Date(project.startDate)):project.dueDate?addDays(startOfDay(new Date(project.dueDate)),-5):today;
const projectEnd=(project:Project,start:Date)=>project.dueDate?startOfDay(new Date(project.dueDate)):addDays(start,4);
function personColor(name:string){let hash=0;for(const char of name)hash=(hash*31+char.charCodeAt(0))%360;return `hsl(${hash} 58% 42%)`;}
function stageRange(project:Project,task:Task,index:number,today:Date){const projectStartDate=projectStart(project,today);const previous=sortedTasks(project)[index-1];const start=previous?.dueDate?addDays(startOfDay(new Date(previous.dueDate)),1):projectStartDate;const end=task.dueDate?startOfDay(new Date(task.dueDate)):addDays(start,1);return{start,end:end<start?start:end};}

export function ResourceSchedule({projects,team,onOpen}:Props){const today=startOfDay(new Date()),rangeStart=monday(today),days=Array.from({length:14},(_,index)=>addDays(rangeStart,index));const unassigned=projects.flatMap(project=>project.tasks.filter(task=>!taskDone(task)&&!task.assignedTo&&!project.assignedTo).map(task=>({project,task})));
 return <section className="resource-schedule"><header className="resource-schedule-head"><div><span>Resource Scheduling</span><h2>Two-week stage schedule</h2><p>The light bar represents the full work order. Colored segments show assigned stages; striped segments are waiting for the previous stage.</p></div><div className="resource-schedule-legend"><i/> Work order <b/> Assigned stage <em/> Blocked</div></header>
 {unassigned.length>0&&<aside className="resource-unassigned"><strong>Unassigned stages</strong><div>{unassigned.map(({project,task})=><button type="button" className={taskBlocked(project,task)?"is-blocked":""} key={task.id} onClick={()=>onOpen(project)}>{taskBlocked(project,task)?"Blocked · ":""}{project.company.shortName} · {task.title}</button>)}</div></aside>}
 <div className="resource-schedule-scroll"><div className="resource-schedule-grid"><div className="resource-schedule-corner"><strong>Team</strong><span>{projects.length} active work orders</span></div><div className="resource-schedule-days">{days.map(day=><div key={day.toISOString()} className={day.getTime()===today.getTime()?"is-today":day.getDay()===0||day.getDay()===6?"is-weekend":""}><strong>{day.toLocaleDateString(undefined,{weekday:"short"})}</strong><span>{day.toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span></div>)}</div>
 {team.map(member=>{const managed=projects.filter(project=>project.assignedTo===member.name);const assignedStages=projects.flatMap(project=>sortedTasks(project).map((task,index)=>({project,task,index,blocked:taskBlocked(project,task)}))).filter(item=>(item.task.assignedTo||item.project.assignedTo)===member.name&&!taskDone(item.task));const actionable=assignedStages.filter(item=>!item.blocked);const load=Math.round(actionable.length/Math.max(1,member.capacity)*100);return <div className="resource-schedule-row" key={member.id}><div className="resource-member"><div><strong>{member.name}</strong><span>{member.role}{assignedStages.some(item=>item.blocked)?` · ${assignedStages.filter(item=>item.blocked).length} blocked`:""}</span></div><em className={load>100?"is-over":load>=80?"is-busy":""}>{load}% load</em></div><div className="resource-track">{days.map(day=><i key={day.toISOString()} className={day.getTime()===today.getTime()?"is-today":day.getDay()===0||day.getDay()===6?"is-weekend":""}/>)}
 {managed.map(project=>{const start=projectStart(project,today),end=projectEnd(project,start),visibleStart=Math.max(start.getTime(),rangeStart.getTime()),visibleEnd=Math.min(end.getTime(),days.at(-1)!.getTime());if(visibleEnd<rangeStart.getTime()||visibleStart>days.at(-1)!.getTime())return null;const left=((visibleStart-rangeStart.getTime())/DAY/14)*100,width=Math.max(7.14,((visibleEnd-visibleStart)/DAY+1)/14*100);return <button type="button" key={`project-${project.id}`} className="resource-project-span" style={{left:`${left}%`,width:`${Math.min(width,100-left)}%`,"--client-color":project.company.primaryColor||"#edbf2d"} as CSSProperties} onClick={()=>onOpen(project)} title={`${project.title} · Project manager: ${member.name}`}><span>{project.title}</span></button>})}
 {assignedStages.map(({project,task,index,blocked})=>{const{start,end}=stageRange(project,task,index,today),visibleStart=Math.max(start.getTime(),rangeStart.getTime()),visibleEnd=Math.min(end.getTime(),days.at(-1)!.getTime());if(visibleEnd<rangeStart.getTime()||visibleStart>days.at(-1)!.getTime())return null;const left=((visibleStart-rangeStart.getTime())/DAY/14)*100,width=Math.max(3.6,((visibleEnd-visibleStart)/DAY+1)/14*100);return <button type="button" key={`task-${task.id}`} className={`resource-stage-segment ${blocked?"is-blocked":""}`} style={{left:`${left}%`,width:`${Math.min(width,100-left)}%`,"--assignee-color":personColor(member.name)} as CSSProperties} onClick={()=>onOpen(project)} title={`${task.title} · ${member.name} · ${blocked?"Blocked by previous stage · ":""}${start.toLocaleDateString()} – ${end.toLocaleDateString()}`}><span>{blocked?"Waiting · ":""}{task.title}</span></button>})}</div></div>})}</div></div></section>}

export function TeamWorkload({projects,team,onOpen}:Props){const today=startOfDay(new Date()),weekEnd=addDays(today,7);return <section className="team-workload-v2">{team.map(member=>{const assignedStages=projects.flatMap(project=>sortedTasks(project).map(task=>({project,task,blocked:taskBlocked(project,task)}))).filter(item=>(item.task.assignedTo||item.project.assignedTo)===member.name&&!taskDone(item.task));const actionable=assignedStages.filter(item=>!item.blocked),blocked=assignedStages.filter(item=>item.blocked);const uniqueProjects=Array.from(new Map(assignedStages.map(item=>[item.project.id,item.project])).values());const dueThisWeek=actionable.filter(({task})=>task.dueDate&&new Date(task.dueDate)>=today&&new Date(task.dueDate)<=weekEnd),overdue=actionable.filter(({task})=>task.dueDate&&new Date(task.dueDate)<today),load=Math.round(actionable.length/Math.max(1,member.capacity)*100),state=load>100?"Over capacity":load>=80?"Near capacity":load===0?"Available":"Balanced";return <article className={`team-workload-card ${load>100?"is-over":load>=80?"is-busy":""}`} key={member.id}><header><div className="ops-avatar">{member.name.split(" ").map(part=>part[0]).join("").slice(0,2)}</div><div><h3>{member.name}</h3><p>{member.role}</p></div><span>{state}</span></header><div className="team-load-meter"><div><strong>{load}%</strong><span>{actionable.length} actionable of {member.capacity} capacity</span></div><i><b style={{width:`${Math.min(100,load)}%`}}/></i></div><dl><div><dt>Due this week</dt><dd>{dueThisWeek.length}</dd></div><div><dt>Actionable</dt><dd>{actionable.length}</dd></div><div><dt>Blocked</dt><dd>{blocked.length}</dd></div><div><dt>Overdue</dt><dd>{overdue.length}</dd></div><div><dt>Projects</dt><dd>{uniqueProjects.length}</dd></div></dl><div className="team-workload-orders">{assignedStages.slice(0,5).map(({project,task,blocked})=><button type="button" className={blocked?"is-blocked":""} key={task.id} onClick={()=>onOpen(project)}><span><small>{project.company.shortName} · {project.title}</small><strong>{blocked?"Waiting · ":""}{task.title}</strong></span><em>{blocked?"Blocked":task.dueDate?new Date(task.dueDate).toLocaleDateString():"No target"}</em></button>)}{!assignedStages.length&&<p>No active stages assigned.</p>}</div></article>})}</section>}
