"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { useParams,useRouter,useSearchParams } from "next/navigation";
import { conditionMatches,getIntakeForm,type IntakeDefinition,type IntakeField } from "@/lib/intake-forms";

type Company={name:string;shortName:string;logo?:string|null;primaryColor:string;secondaryColor:string;brandTextColor?:string};
type Project={id:number;name:string;address?:string|null;type?:string|null};
type Value=string|boolean|string[];
const PROPERTY_TYPES=["Retail","Office","Mixed-use","Industrial / warehouse","Residential","Hospitality","Medical","Land / development","Other"];
const init=(services:IntakeDefinition[])=>Object.fromEntries(services.flatMap(service=>service.fields.map(field=>[`${service.slug}.${field.key}`,field.type==="multi_select"?[]:field.type==="checkbox"?false:field.key==="priority"?"normal":""]))) as Record<string,Value>;
const empty=(value:Value|undefined)=>Array.isArray(value)?!value.length:typeof value==="boolean"?!value:!String(value||"").trim();

export default function RequestComposer(){
 const params=useParams(),router=useRouter(),search=useSearchParams();const companySlug=Array.isArray(params.company)?params.company[0]:String(params.company||"");
 const[company,setCompany]=useState<Company|null>(null),[services,setServices]=useState<IntakeDefinition[]>([]),[projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const[mode,setMode]=useState<"new"|"existing">("new"),[projectId,setProjectId]=useState(""),[projectName,setProjectName]=useState(""),[propertyType,setPropertyType]=useState(""),[address,setAddress]=useState(""),[space,setSpace]=useState(""),[contactName,setContactName]=useState(""),[contactEmail,setContactEmail]=useState(""),[priority,setPriority]=useState("normal"),[selected,setSelected]=useState<string[]>([]),[answers,setAnswers]=useState<Record<string,Value>>({}),[submitted,setSubmitted]=useState(false);
 useEffect(()=>{if(!companySlug)return;if(localStorage.getItem("upz_company_slug")!==companySlug){router.push("/login");return}Promise.all([fetch(`/api/portal/companies/${companySlug}`).then(r=>r.json()),fetch(`/api/portal/companies/${companySlug}/services`,{cache:"no-store"}).then(r=>r.ok?r.json():[]),fetch(`/api/portal/companies/${companySlug}/projects`,{cache:"no-store"}).then(r=>r.ok?r.json():[])]).then(([companyData,serviceData,projectData])=>{const list=Array.isArray(serviceData)?serviceData:[];setCompany(companyData);setServices(list);setProjects(Array.isArray(projectData)?projectData:[]);setAnswers(init(list));const preset=search.get("service");if(preset&&list.some(item=>item.slug===preset))setSelected([preset]);setContactName(localStorage.getItem(`upz_contact_name_${companySlug}`)||companyData?.name||"");setContactEmail(localStorage.getItem(`upz_contact_email_${companySlug}`)||"");const requested=search.get("engagementId")||search.get("portfolioId");if(requested){setMode("existing");setProjectId(requested)}}).finally(()=>setLoading(false))},[companySlug,router,search]);
 const chosen=services.filter(service=>selected.includes(service.slug));const activeProject=projects.find(project=>String(project.id)===projectId);
 useEffect(()=>{if(mode==="existing"&&activeProject){setProjectName(activeProject.name);setAddress(activeProject.address||"");setPropertyType(activeProject.type||"")}},[mode,activeProject]);
 const key=(service:string,field:string)=>`${service}.${field}`;const update=(service:string,field:string,value:Value)=>setAnswers(current=>({...current,[key(service,field)]:value}));
 const scoped=(service:IntakeDefinition)=>Object.fromEntries(service.fields.map(field=>[field.key,answers[key(service.slug,field.key)]]));
 function visible(service:IntakeDefinition,field:IntakeField){return conditionMatches(field.condition,scoped(service))}
 function optionsFor(service:IntakeDefinition,field:IntakeField){if(service.slug==="signage"&&field.key==="signageType"&&propertyType==="Office")return(field.options||[]).filter(option=>option!=="Storefront vinyl");return field.options||[]}
 function render(service:IntakeDefinition,field:IntakeField){if(!visible(service,field)||["contactName","contactEmail","priority","propertyAddress","attachments","notes"].includes(field.key))return null;const value=answers[key(service.slug,field.key)]??"",className=field.wide?"composer-wide":"";if(field.type==="multi_select")return <fieldset className={`composer-choice ${className}`} key={field.key}><legend>{field.label}{field.required&&" *"}</legend>{field.helpText&&<p>{field.helpText}</p>}<div>{optionsFor(service,field).map(option=>{const list=Array.isArray(value)?value:[],on=list.includes(option);return <button type="button" className={on?"selected":""} onClick={()=>update(service.slug,field.key,on?list.filter(item=>item!==option):[...list,option])} key={option}><i>{on?"✓":""}</i>{option}</button>})}</div></fieldset>;if(field.type==="select")return <label className={className} key={field.key}>{field.label}<select value={String(value)} onChange={e=>update(service.slug,field.key,e.target.value)}><option value="">Select an option</option>{optionsFor(service,field).map(option=><option key={option}>{option}</option>)}</select></label>;if(field.type==="textarea")return <label className={className} key={field.key}>{field.label}<textarea value={String(value)} onChange={e=>update(service.slug,field.key,e.target.value)} placeholder={field.placeholder}/></label>;if(field.type==="checkbox")return <label className={`composer-check ${className}`} key={field.key}><input type="checkbox" checked={Boolean(value)} onChange={e=>update(service.slug,field.key,e.target.checked)}/>{field.label}</label>;return <label className={className} key={field.key}>{field.label}<input type={field.type==="address"?"text":field.type} value={String(value)} onChange={e=>update(service.slug,field.key,e.target.value)} placeholder={field.placeholder}/></label>}
 const summary=useMemo(()=>chosen.map(service=>({service,missing:service.fields.filter(field=>visible(service,field)&&field.required&&!["contactName","contactEmail","priority","propertyAddress"].includes(field.key)&&empty(answers[key(service.slug,field.key)])).length})),[chosen,answers,propertyType]);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage("");if(mode==="new"&&!projectName.trim())return setMessage("Add a project or property name.");if(mode==="existing"&&!projectId)return setMessage("Choose an existing project.");if(!propertyType)return setMessage("Choose the property type.");if(!selected.length)return setMessage("Select at least one service.");const incomplete=summary.find(item=>item.missing);if(incomplete)return setMessage(`Complete the required ${incomplete.service.name} fields.`);if(!contactEmail.trim())return setMessage("Add a contact email.");setSaving(true);try{localStorage.setItem(`upz_contact_name_${companySlug}`,contactName);localStorage.setItem(`upz_contact_email_${companySlug}`,contactEmail);for(const service of chosen){const serviceAnswers=scoped(service),location=space.trim()||propertyType,workOrderTitle=`${projectName.trim()} · ${location} · ${service.name}`;const checklistSelections=service.fields.filter(field=>field.checklistStage&&Array.isArray(serviceAnswers[field.key])&&(serviceAnswers[field.key] as string[]).length).map(field=>({fieldKey:field.key,fieldLabel:field.label,stage:field.checklistStage,items:serviceAnswers[field.key]}));const response=await fetch(`/api/portal/companies/${companySlug}/requests`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({service:service.name,serviceSlug:service.slug,engagementId:mode==="existing"?projectId:undefined,engagementName:projectName.trim(),portfolioName:projectName.trim(),locationName:location,workOrderTitle,propertyAddress:address.trim(),priority,answers:{contactName,contactEmail,propertyType,propertyAddress:address,...serviceAnswers},checklistSelections,requestGroup:{projectName:projectName.trim(),propertyType,address,space,services:selected}})});const data=await response.json();if(!response.ok)throw new Error(data?.error||`Unable to submit ${service.name}`)}setSubmitted(true)}catch(error:any){setMessage(error.message||"Unable to submit request")}finally{setSaving(false)}}
 if(loading)return <main className="portal-page composer-loading">Loading request composer...</main>;if(!company)return <main className="portal-page">Portal unavailable.</main>;const style={"--company-primary":company.primaryColor,"--company-secondary":company.secondaryColor,"--company-on-primary":company.brandTextColor||company.secondaryColor||"#fff"} as React.CSSProperties;
 if(submitted)return <main className="portal-page request-composer" style={style}><section className="composer-success">{company.logo&&<img src={company.logo} alt=""/>}<span>Request submitted</span><h1>Your project request is under review.</h1><p>{selected.length} service{selected.length===1?"":"s"} were submitted for {projectName}.</p><div><Link href={`/portal/${companySlug}`}>Return to Portal</Link><Link href={`/portal/${companySlug}/projects`}>View Projects & Requests</Link></div></section></main>;
 return <main className="portal-page request-composer" style={style}><nav className="portal-request-nav"><Link href={`/portal/${companySlug}`}>← Portal Home</Link><Link href={`/portal/${companySlug}/projects`}>Projects & Requests</Link><span>New Project Request</span></nav><form onSubmit={submit}><header className="composer-header">{company.logo&&<img src={company.logo} alt=""/>}<div><span>{company.shortName} · Project Request</span><h1>Tell us about the property, then select the services you need.</h1></div></header>{message&&<div className="composer-error">{message}</div>}
 <div className="composer-layout"><div className="composer-main"><section className="composer-section"><div className="composer-section-title"><span>01</span><div><h2>Property information</h2><p>Shared once across every requested service.</p></div></div><div className="composer-grid"><div className="composer-mode composer-wide"><button type="button" className={mode==="new"?"active":""} onClick={()=>setMode("new")}>New project</button><button type="button" className={mode==="existing"?"active":""} onClick={()=>setMode("existing")}>Existing project</button></div>{mode==="existing"?<label className="composer-wide">Choose project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select a project</option>{projects.map(project=><option value={project.id} key={project.id}>{project.name}{project.address?` — ${project.address}`:""}</option>)}</select></label>:<label className="composer-wide">Project / property name<input value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="123 Fifth Avenue"/></label>}<label>Property type<select value={propertyType} onChange={e=>setPropertyType(e.target.value)}><option value="">Choose property type</option>{PROPERTY_TYPES.map(type=><option key={type}>{type}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="composer-wide">Property address<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Full street address"/></label><label className="composer-wide">Specific suite, floor, storefront, or area<input value={space} onChange={e=>setSpace(e.target.value)} placeholder="Optional exact location"/></label><label>Contact name<input value={contactName} onChange={e=>setContactName(e.target.value)}/></label><label>Contact email<input type="email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)}/></label></div></section>
 <section className="composer-section"><div className="composer-section-title"><span>02</span><div><h2>Select services</h2><p>Choose one or more. Only relevant questions will open below.</p></div></div><div className="composer-services">{services.map(service=>{const on=selected.includes(service.slug);return <button type="button" key={service.slug} className={on?"selected":""} onClick={()=>setSelected(on?selected.filter(item=>item!==service.slug):[...selected,service.slug])}><i>{on?"✓":"+"}</i><strong>{service.name}</strong><span>{service.description}</span></button>})}</div></section>
 {chosen.map((service,index)=><section className="composer-section composer-service-section" key={service.slug}><div className="composer-section-title"><span>{String(index+3).padStart(2,"0")}</span><div><h2>{service.name}</h2><p>{service.description}</p></div><button type="button" onClick={()=>setSelected(selected.filter(item=>item!==service.slug))}>Remove</button></div><div className="composer-grid">{service.fields.map(field=>render(service,field))}</div></section>)}</div>
 <aside className="composer-summary"><span>Request summary</span><h3>{projectName||"Untitled project"}</h3><p>{[propertyType,space,address].filter(Boolean).join(" · ")||"Complete property information"}</p><div>{summary.map(item=><article key={item.service.slug}><strong>{item.service.name}</strong><em className={item.missing?"missing":""}>{item.missing?`${item.missing} required`:"Ready"}</em></article>)}{!summary.length&&<small>No services selected yet.</small>}</div><button type="submit" disabled={saving}>{saving?"Submitting...":"Review & Submit Request"}</button></aside></div></form></main>;
}
