"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { useParams,useRouter,useSearchParams } from "next/navigation";
import { conditionMatches,type IntakeDefinition,type IntakeField } from "@/lib/intake-forms";
import { useCartStore } from "@/store/cart-store";

type Company={name:string;shortName:string;logo?:string|null;primaryColor:string;secondaryColor:string;brandTextColor?:string;heroTitle?:string;heroText?:string};
type Project={id:number;name:string;address?:string|null;type?:string|null};
type Value=string|boolean|string[];
const TYPES=["Retail","Office","Mixed-use","Industrial / warehouse","Residential","Hospitality","Medical","Land / development","Other"];
const EMPTY=(v:Value|undefined)=>Array.isArray(v)?!v.length:typeof v==="boolean"?!v:!String(v||"").trim();
const clean=(value:unknown)=>Array.isArray(value)?value.filter(Boolean).join(", "):String(value||"").trim();

export default function RequestComposer(){
 const params=useParams(),router=useRouter(),search=useSearchParams(),slug=Array.isArray(params.company)?params.company[0]:String(params.company||"");
 const cart=useCartStore();
 const[company,setCompany]=useState<Company|null>(null),[services,setServices]=useState<IntakeDefinition[]>([]),[projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const[mode,setMode]=useState<"new"|"existing">("new"),[projectId,setProjectId]=useState(""),[projectName,setProjectName]=useState(""),[propertyType,setPropertyType]=useState(""),[address,setAddress]=useState(""),[space,setSpace]=useState(""),[contactName,setContactName]=useState(""),[contactEmail,setContactEmail]=useState(""),[priority,setPriority]=useState("normal"),[attachments,setAttachments]=useState(""),[notes,setNotes]=useState(""),[selected,setSelected]=useState<string[]>([]),[answers,setAnswers]=useState<Record<string,Value>>({});

 useEffect(()=>{if(!slug)return;if(localStorage.getItem("upz_company_slug")!==slug){router.push("/login");return}cart.hydrate();Promise.all([fetch(`/api/portal/companies/${slug}`).then(r=>r.json()),fetch(`/api/portal/companies/${slug}/services`,{cache:"no-store"}).then(r=>r.ok?r.json():[]),fetch(`/api/portal/companies/${slug}/projects`,{cache:"no-store"}).then(r=>r.ok?r.json():[])]).then(([c,s,p])=>{setCompany(c);setServices(Array.isArray(s)?s:[]);setProjects(Array.isArray(p)?p:[]);setContactName(localStorage.getItem(`upz_contact_name_${slug}`)||c.name||"");setContactEmail(localStorage.getItem(`upz_contact_email_${slug}`)||"");const existing=cart.items.filter(item=>item.itemType==="service_request"&&item.companySlug===slug).map(item=>item.serviceSlug).filter(Boolean) as string[];const preset=search.get("service");setSelected(Array.from(new Set([...existing,...(preset?[preset]:[])])))}).finally(()=>setLoading(false))},[slug,router,search]);
 const active=projects.find(p=>String(p.id)===projectId);useEffect(()=>{if(mode==="existing"&&active){setProjectName(active.name);setAddress(active.address||"");setPropertyType(active.type||"")}},[mode,active]);
 const chosen=services.filter(s=>selected.includes(s.slug)),k=(s:string,f:string)=>`${s}.${f}`,scoped=(s:IntakeDefinition)=>Object.fromEntries(s.fields.map(f=>[f.key,answers[k(s.slug,f.key)]]));
 function visible(s:IntakeDefinition,f:IntakeField){return conditionMatches(f.condition,scoped(s))}function update(s:string,f:string,v:Value){setAnswers(a=>({...a,[k(s,f)]:v}))}
 function options(s:IntakeDefinition,f:IntakeField){let list=f.options||[];if(s.slug==="signage"&&f.key==="signageType"&&propertyType==="Office")list=list.filter(x=>x!=="Storefront vinyl");return list}
 function serviceSummary(service:IntakeDefinition){const values=service.fields.map(field=>clean(answers[k(service.slug,field.key)])).filter(Boolean);return values.slice(0,2).join(" · ")||"Complete service details"}
 function setService(service:IntakeDefinition,on:boolean){if(on){setSelected(current=>current.includes(service.slug)?current:[...current,service.slug]);cart.addItem({id:`request-${slug}-${service.slug}`,itemType:"service_request",name:service.name,image:service.imageUrl||"/service-placeholders/general.svg",quantity:1,companySlug:slug,companyName:company?.name,projectName:projectName||"New project",address:address||projectName||"Property details pending",serviceSlug:service.slug,requestSummary:serviceSummary(service),requestHref:`/portal/${slug}/request/review`});cart.openCart()}else{setSelected(current=>current.filter(x=>x!==service.slug));cart.removeItem(`request-${slug}-${service.slug}`)}}
 useEffect(()=>{const cartSlugs=cart.items.filter(item=>item.itemType==="service_request"&&item.companySlug===slug).map(item=>item.serviceSlug).filter(Boolean) as string[];setSelected(current=>current.filter(item=>cartSlugs.includes(item)))},[cart.items,slug]);
 useEffect(()=>{chosen.forEach(service=>cart.addItem({id:`request-${slug}-${service.slug}`,itemType:"service_request",name:service.name,image:service.imageUrl||"/service-placeholders/general.svg",quantity:1,companySlug:slug,companyName:company?.name,projectName:projectName||"New project",address:address||projectName||"Property details pending",serviceSlug:service.slug,requestSummary:serviceSummary(service),requestHref:`/portal/${slug}/request/review`}))},[projectName,address,answers,selected]);

 function render(s:IntakeDefinition,f:IntakeField){if(!visible(s,f)||["contactName","contactEmail","priority","propertyAddress","attachments","fileLinks","notes"].includes(f.key))return null;const v=answers[k(s.slug,f.key)]??"",cls=f.wide?"composer-wide":"";if(f.type==="multi_select")return <fieldset key={f.key} className={`composer-choice ${cls}`}><legend>{f.label}{f.required&&" *"}</legend>{f.helpText&&<p>{f.helpText}</p>}<div>{options(s,f).map(o=>{const a=Array.isArray(v)?v:[],on=a.includes(o);return <button type="button" key={o} className={on?"selected":""} onClick={()=>update(s.slug,f.key,on?a.filter(x=>x!==o):[...a,o])}><i>{on?"✓":""}</i>{o}</button>})}</div></fieldset>;if(f.type==="select")return <label key={f.key} className={cls}>{f.label}<select value={String(v)} onChange={e=>update(s.slug,f.key,e.target.value)}><option value="">Select</option>{options(s,f).map(o=><option key={o}>{o}</option>)}</select></label>;if(f.type==="textarea")return <label key={f.key} className={cls}>{f.label}<textarea value={String(v)} onChange={e=>update(s.slug,f.key,e.target.value)} placeholder={f.placeholder}/></label>;if(f.type==="checkbox")return <label key={f.key} className={`composer-check ${cls}`}><input type="checkbox" checked={Boolean(v)} onChange={e=>update(s.slug,f.key,e.target.checked)}/>{f.label}</label>;return <label key={f.key} className={cls}>{f.label}<input type={f.type==="address"?"text":f.type} value={String(v)} onChange={e=>update(s.slug,f.key,e.target.value)} placeholder={f.placeholder}/></label>}
 const summary=useMemo(()=>chosen.map(service=>({service,missing:service.fields.filter(f=>visible(service,f)&&f.required&&!["contactName","contactEmail","priority","propertyAddress"].includes(f.key)&&EMPTY(answers[k(service.slug,f.key)])).length})),[chosen,answers,propertyType]);
 function review(){setMessage("");if(!projectName.trim())return setMessage("Add or choose a project.");if(!propertyType)return setMessage("Choose a property type.");if(!address.trim())return setMessage("Add the property address.");if(!contactEmail.trim())return setMessage("Add a contact email.");if(!selected.length)return setMessage("Add at least one service to the cart.");const bad=summary.find(x=>x.missing);if(bad)return setMessage(`Complete the required ${bad.service.name} information.`);localStorage.setItem(`upz_contact_name_${slug}`,contactName);localStorage.setItem(`upz_contact_email_${slug}`,contactEmail);sessionStorage.setItem(`upz_request_cart_${slug}`,JSON.stringify({mode,projectId,projectName,propertyType,address,space,contactName,contactEmail,priority,attachments,notes,selected,services:chosen.map(s=>({slug:s.slug,name:s.name,answers:scoped(s),fields:s.fields}))}));cart.closeCart();router.push(`/portal/${slug}/request/review`)}
 if(loading)return <main className="portal-page"><section className="portal-simple-state"><h1>Loading request...</h1></section></main>;if(!company)return <main className="portal-page"><section className="portal-simple-state"><h1>Portal unavailable</h1></section></main>;
 const style={"--company-primary":company.primaryColor,"--company-secondary":company.secondaryColor,"--company-on-primary":company.brandTextColor||"#fff"}as React.CSSProperties;
 return <main className="portal-page portal-request-workspace" style={style}>
  <section className="portal-hero portal-request-hero"><div className="upz-wrap portal-hero-inner"><div><div className="portal-eyebrow">Project Request</div><h1>Add services to this property.</h1><p>Enter the property once, then build a coordinated request using the same cart as merchandise.</p><div className="portal-actions"><Link href={`/portal/${slug}`}>Portal Home</Link><Link href={`/portal/${slug}/projects`}>Projects & Requests</Link></div></div><div className="portal-brand-card">{company.logo&&<img src={company.logo} alt=""/>}<h2>{company.name}</h2><p>{selected.length} service{selected.length===1?"":"s"} currently in the request cart.</p></div></div></section>
  {message&&<div className="upz-wrap"><div className="composer-error">{message}</div></div>}
  <section className="portal-section"><div className="upz-wrap"><div className="portal-section-heading"><div><span>Property</span><h2>Project information</h2><p>Shared across every selected service.</p></div></div><div className="composer-section portal-request-panel"><div className="composer-grid"><div className="composer-mode composer-wide"><button type="button" className={mode==="new"?"active":""} onClick={()=>setMode("new")}>New project</button><button type="button" className={mode==="existing"?"active":""} onClick={()=>setMode("existing")}>Existing project</button></div>{mode==="existing"?<label className="composer-wide">Project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Select</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}{p.address?` — ${p.address}`:""}</option>)}</select></label>:<label className="composer-wide">Project / property name<input value={projectName} onChange={e=>setProjectName(e.target.value)}/></label>}<label>Property type<select value={propertyType} onChange={e=>setPropertyType(e.target.value)}><option value="">Select</option>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="composer-wide">Address<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="composer-wide">Suite, floor, storefront, or area <small>(optional)</small><input value={space} onChange={e=>setSpace(e.target.value)}/></label><label>Contact name<input value={contactName} onChange={e=>setContactName(e.target.value)}/></label><label>Contact email<input type="email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)}/></label></div></div></div></section>
  <section className="portal-section portal-premium-services portal-request-services"><div className="upz-wrap"><div className="portal-section-heading portal-dark-heading"><div><span>Services</span><h2>Build the request cart</h2><p>Select a service to add it. Remove it here or directly from the cart drawer.</p></div></div><div className="portal-premium-service-grid">{services.map(service=>{const on=selected.includes(service.slug);return <button type="button" key={service.slug} className={`portal-premium-service-card portal-request-service-card ${on?"selected":""}`} onClick={()=>setService(service,!on)}><div className="portal-service-card-image"><img src={service.imageUrl||"/service-placeholders/general.svg"} alt=""/></div><div className="portal-service-card-copy"><span>{on?"Added to request":"Creative Service"}</span><h3>{service.name}</h3><p>{service.description}</p><strong>{on?"Remove service":"Add service"} <b>{on?"×":"+"}</b></strong></div></button>})}</div></div></section>
  {chosen.map(service=><section className="portal-section portal-request-detail" key={service.slug}><div className="upz-wrap"><div className="portal-section-heading"><div><span>Service Scope</span><h2>{service.name}</h2><p>Only information that changes this service workflow.</p></div><button type="button" className="portal-section-button" onClick={()=>setService(service,false)}>Remove Service</button></div><div className="composer-section portal-request-panel"><div className="composer-grid">{service.fields.map(field=>render(service,field))}</div></div></div></section>)}
  {chosen.length>0&&<section className="portal-section"><div className="upz-wrap"><div className="portal-section-heading"><div><span>Shared Details</span><h2>Files and final notes</h2></div></div><div className="composer-section portal-request-panel"><div className="composer-grid"><label className="composer-wide">File or folder links<textarea value={attachments} onChange={e=>setAttachments(e.target.value)} placeholder="Drive, Dropbox, plans, photos, or artwork links"/></label><label className="composer-wide">Additional notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Only details not covered above"/></label></div></div></div></section>}
  <div className="portal-request-bottom-bar"><div><strong>{projectName||"New project"}</strong><span>{selected.length} service{selected.length===1?"":"s"} in request cart</span></div><button type="button" onClick={()=>cart.openCart()}>View Request Cart</button><button type="button" className="primary" onClick={review}>Review Request</button></div>
 </main>;
}
